import { test, expect } from "./fixtures.js"
import { expectNoPageOverflow } from "./helpers/responsive.js"

test("项目助手确认、跨页恢复与390px键盘路径", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  const project = await projectFactory({ title: "助手验收 · 雾港记事" })
  await openProjectWorkbench(project, "writing")
  const toggle = page.getByRole("button", { name: "项目助手", exact: true })
  await expect(toggle).toBeVisible()
  await toggle.click()
  const panel = page.locator("#project-assistant-panel")
  await expect(panel).toBeVisible()
  await panel.locator("#assistant-input").fill("明天提醒我核对人物年龄")
  await panel.getByRole("button", { name: "发送", exact: true }).click()
  await expect(panel.getByRole("button", { name: "确认所选修改" })).toBeVisible({ timeout: 30000 })
  await panel.getByRole("button", { name: "确认所选修改" }).click()
  await expect(panel.getByRole("listitem").filter({ hasText: "已加入待办" })).toBeVisible()
  const originalSessionId = await panel.locator("#assistant-session").inputValue()
  await panel.locator("#assistant-input").fill("这是未提交的后续问题")
  await page.evaluate(() => window.router.navigate("world", "bible"))
  await expect(panel.locator("#assistant-input")).toHaveValue("这是未提交的后续问题")
  await page.reload()
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  await expect(panel.locator("#assistant-input")).toHaveValue("这是未提交的后续问题")
  await expect(panel.getByText("已确认：记录年龄核对事项。", { exact: true })).toBeVisible()
  await page.evaluate(() => window.router.navigate("generate"))
  await page.getByRole("button", { name: "打开这次讨论", exact: true }).click()
  await expect(panel).toBeVisible()
  await expect(panel.locator("#assistant-session")).not.toHaveValue(originalSessionId)
  await expect(panel.locator("#assistant-session")).not.toHaveValue("")
  await expect(panel.locator("#assistant-session")).toBeEnabled()
  await expect(page.locator("[data-owner-ai-drawer]")).toBeHidden()
  await panel.locator("#assistant-input").click()
  const worldSessionId = await panel.locator("#assistant-session").inputValue()
  await page.screenshot({ path: testInfo.outputPath("assistant-cocreation.png"), fullPage: true })
  await page.reload()
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  await expect(panel.locator("#assistant-session")).toHaveValue(worldSessionId)
  await panel.locator("#assistant-session").selectOption(originalSessionId)
  await expect(panel.locator("#assistant-input")).toHaveValue("这是未提交的后续问题")
  await page.screenshot({ path: testInfo.outputPath("assistant-desktop.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(panel).toHaveAttribute("role", "dialog")
  await expectNoPageOverflow(page)
  await panel.locator("#assistant-input").focus()
  await page.keyboard.press("Escape")
  await expect(panel).toBeHidden()
  await toggle.click()
  await expect(panel).toBeVisible()
  await panel.getByRole("button", { name: "提醒", exact: true }).click()
  await panel.locator("summary").filter({ hasText: "主动服务设置" }).click()
  await panel.getByLabel("内容变化后主动检查").check()
  await panel.getByRole("button", { name: "保存设置", exact: true }).click()
  await expect(panel.getByText("设置已保存。", { exact: true })).toBeVisible()
  await expectNoPageOverflow(page)
  await page.screenshot({ path: testInfo.outputPath("assistant-mobile.png"), fullPage: true })
  expect(browserErrors).toEqual([])
})
