import { test, expect } from "./fixtures.js"
import { createDraft, getLatestDraft } from "./helpers/api-client.js"

test("逐场景理解从作者入口连续推进，重载恢复进度且可暂停", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  const project = await projectFactory({ title: "顺序理解 · 临时合成验收" })
  for (const [index, content] of ["天亮了。", "下雨了。"].entries()) {
    await createDraft(project.id, index + 1, `第${index + 1}章`, content)
  }
  await openProjectWorkbench(project, "project-settings")
  await page.getByRole("tab", { name: "高级导入", exact: true }).click()
  const flow = page.locator(".reading-flow")
  await flow.locator("summary").click()
  page.once("dialog", dialog => dialog.accept())
  await flow.getByRole("button", { name: "启用逐场景理解…" }).click()
  await flow.getByLabel("读到第几章").fill("2")
  await flow.getByLabel("本次最多调用模型").fill("1")
  await flow.getByRole("button", { name: "查看理解范围" }).click()
  await expect(flow).toContainText("先准备场景边界，完成后逐场景理解")
  await flow.getByRole("button", { name: "确认并开始理解" }).click()
  await expect(flow).toContainText("本次调用额度已用完", { timeout: 60000 })
  await flow.getByLabel("本次追加调用上限").fill("8")
  await flow.getByRole("button", { name: "查看理解范围" }).click()
  await expect(flow).toContainText("本次继续读取 2 个场景")
  await flow.getByRole("button", { name: "确认并开始理解" }).click()
  await expect(flow).toContainText("所选范围理解已更新", { timeout: 60000 })
  await expect(flow).toContainText("2 / 2 场景")
  await page.reload()
  await page.getByRole("tab", { name: "高级导入", exact: true }).click()
  await flow.locator("summary").click()
  await expect(flow).toContainText("所选范围理解已更新")
  await page.evaluate(() => window.router.navigate("writing"))
  await page.locator('[data-action="writing-ai-menu"]').click()
  await page.getByRole("button", { name: "理解与整理正文…" }).click()
  await expect(flow).toContainText("所选范围理解已更新")
  await expect(page.getByRole("button", { name: "确认并开始提取" })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await flow.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("reading-mobile.png"), fullPage: true })
  await flow.getByRole("checkbox", { name: "重新核对已有场景" }).check()
  await flow.getByLabel("重新核对什么").selectOption("observation")
  await flow.getByLabel("查找名称或观察文字").fill("下雨")
  await flow.getByRole("button", { name: "查找已读内容" }).click()
  const target = flow.getByLabel("核对目标")
  await expect(target.locator("option")).toHaveCount(2)
  await target.selectOption({ index: 1 })
  await flow.getByLabel("本次最多调用模型").fill("4")
  await flow.getByRole("button", { name: "查看理解范围" }).click()
  await expect(flow).toContainText("保留前 1 场已核实的理解")
  await expect(flow).toContainText("从第 2 场起重新核对")
  await expect(flow).toContainText("核对目标：")
  await flow.locator(".reading-confirmation").scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath("reading-recompute-mobile.png"), fullPage: true })
  await flow.getByRole("button", { name: "确认并开始理解" }).click()
  await expect(flow).toContainText("所选范围理解已更新", { timeout: 60000 })
  await expect(flow).toContainText("2 / 2 场景")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  page.once("dialog", dialog => dialog.accept())
  await flow.getByRole("button", { name: "暂停自动理解…" }).click()
  await expect(flow).toContainText("已暂停，历史结果保留")
  expect((await getLatestDraft(project.id, 1)).content).toBe("天亮了。")
  expect(browserErrors).toEqual([])
})

test("保存选区和润色意图进入同一前瞻，刷新不生成", async ({ page, projectFactory, openProjectWorkbench, browserErrors }) => {
  const project = await projectFactory({ title: "前瞻焦点 · 临时合成验收" })
  const prose = "她接受了旧敌的帮助。\n窗外的雨还没有停。"
  await createDraft(project.id, 1, "有限合作", prose)
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "1" })))
  await page.getByRole("button", { name: /^打开第 1 章/ }).click()
  const editor = page.locator("#writing-editor")
  await expect(editor).toHaveValue(prose)
  await editor.evaluate(element => {
    element.focus()
    element.setSelectionRange(2, 8)
    element.dispatchEvent(new Event("select", { bubbles: true }))
  })
  const generated = []
  page.on("request", request => { if (request.url().includes("/assistant/forecasts/evaluate")) generated.push(request) })
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  const panel = page.locator("#project-assistant-panel")
  await panel.getByRole("button", { name: "下一步", exact: true }).click()
  const forecast = panel.getByRole("region", { name: "下一步建议" })
  await forecast.getByLabel("当前写作意图").selectOption("polish")
  const sent = page.waitForRequest(request => request.url().includes("/assistant/forecasts/feed") && request.postDataJSON()?.context?.task_hint === "polish")
  await forecast.getByRole("button", { name: "刷新资料", exact: true }).click()
  const context = (await sent).postDataJSON().context
  expect(context.selected_range).toEqual({ start_offset: 2, end_offset: 8 })
  expect(context.task_hint).toBe("polish")
  expect(context.expected_source_hash).toBeTruthy()
  expect((await getLatestDraft(project.id, 1)).content).toBe(prose)
  expect(generated).toEqual([])
  expect(browserErrors).toEqual([])
})

test("持久理解可修正，切换标签保护输入，重载后保留作者历史", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  const project = await projectFactory({ title: "持久理解 · 临时合成验收" })
  await createDraft(project.id, 1, "有限合作", "她接受了旧敌的帮助。")
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "1" })))
  await page.getByRole("button", { name: /^打开第 1 章/ }).click()
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  const panel = page.locator("#project-assistant-panel")
  await panel.getByRole("button", { name: "试改", exact: true }).click()
  const creative = panel.getByRole("region", { name: "隔离试改" })
  await creative.getByLabel("想解决什么").fill("核对合作意味着什么，并保留理解")
  await creative.getByLabel("这次怎样帮助你").selectOption("deep_review")
  await creative.getByRole("checkbox", { name: "当前正文工作稿" }).check()
  await creative.getByText("参考范围、连接与自定义检查", { exact: true }).click()
  await creative.getByRole("checkbox", { name: /保留.*理解/ }).check()
  await creative.getByRole("button", { name: "开始调查与试改" }).click()
  await expect(creative.getByText("本轮处理完成", { exact: true }).first()).toBeVisible({ timeout: 60000 })
  const understanding = creative.locator(".understanding")
  await understanding.locator("summary").click()
  await expect(understanding).toContainText("她接受帮助，但信任程度仍需核对。")
  await understanding.getByRole("button", { name: "修正", exact: true }).click()
  await understanding.getByLabel("修正后的理解").fill("她只同意交换线索，仍然保留戒心。")
  page.once("dialog", dialog => dialog.dismiss())
  await panel.getByRole("button", { name: "讨论", exact: true }).click()
  await expect(understanding.getByLabel("修正后的理解")).toHaveValue("她只同意交换线索，仍然保留戒心。")
  await understanding.getByRole("button", { name: "保存修正", exact: true }).click()
  await expect(understanding).toContainText("修正已保存")
  await understanding.getByRole("button", { name: "查看历史", exact: true }).click()
  await expect(understanding.getByRole("list")).toContainText("她接受帮助，但信任程度仍需核对。")
  await page.setViewportSize({ width: 390, height: 844 })
  await understanding.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("cognition-mobile.png"), fullPage: true })
  await page.reload()
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  await panel.getByRole("button", { name: "试改", exact: true }).click()
  await understanding.locator("summary").click()
  await expect(understanding).toContainText("她只同意交换线索，仍然保留戒心。")
  expect(browserErrors).toEqual([])
})

test("前瞻与两种真实试改：保存保护、确认、恢复和窄屏", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  const project = await projectFactory({ title: "创作试验 · 临时合成验收" })
  const original = "她接受了旧敌的帮助。窗外的雨还没有停。"
  const initial = "她接受了旧敌的帮助。"
  await createDraft(project.id, 1, "有限合作", initial)
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "1" })))
  await page.getByRole("button", { name: /^打开第 1 章/ }).click()
  const editor = page.locator("#writing-editor")
  await expect(editor).toHaveValue(initial)
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  const panel = page.locator("#project-assistant-panel")
  await panel.getByRole("button", { name: "下一步", exact: true }).click()
  const forecast = panel.getByRole("region", { name: "下一步建议" })
  await expect(forecast.getByText("还没有分析这一处。已有保存资料可以直接查看。")).toBeVisible()
  await editor.dispatchEvent("compositionstart")
  await editor.fill(original)
  await expect(forecast.getByRole("button", { name: "帮我想下一步" })).toBeDisabled()
  await expect(editor).toBeFocused()
  await editor.dispatchEvent("compositionend")
  await page.locator("#btn-autosave").click()
  await expect(forecast.getByRole("button", { name: "帮我想下一步" })).toBeEnabled()
  expect((await getLatestDraft(project.id, 1)).content).toBe(original)
  await forecast.getByRole("button", { name: "帮我想下一步" }).click()
  await expect(forecast.getByRole("heading", { name: "保留一条谨慎合作的退路" })).toBeVisible({ timeout: 45000 })
  await forecast.getByRole("article").filter({ hasText: "保留一条谨慎合作的退路" }).getByRole("button", { name: "加入稍后处理" }).click()
  await expect(forecast.getByRole("button", { name: "确认这一项", exact: true })).toBeEnabled()
  await forecast.getByRole("button", { name: "确认这一项", exact: true }).click()
  await expect(forecast.getByText("这一项已完成。", { exact: true })).toBeVisible()
  expect((await getLatestDraft(project.id, 1)).content).toBe(original)
  await panel.getByRole("button", { name: "试改", exact: true }).click()
  const creative = panel.getByRole("region", { name: "隔离试改" })
  await creative.getByLabel("想解决什么").fill("补足合作的动机，比较保留谨慎与交换条件")
  await creative.getByLabel("必须保留什么").fill("不提前揭露身份")
  await creative.getByRole("checkbox", { name: "当前正文工作稿" }).check()
  await creative.getByRole("button", { name: "开始调查与试改" }).click()
  await expect(creative.getByText("本轮处理完成", { exact: true }).first()).toBeVisible({ timeout: 60000 })
  await expect(creative.locator(".creative-trial-button")).toHaveCount(2)
  expect((await getLatestDraft(project.id, 1)).content).toBe(original)
  await creative.locator(".creative-trial-button").filter({ hasText: "保留谨慎" }).click()
  await expect(creative.getByText("这一版检查通过", { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath("creative-desktop.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("creative-mobile.png"), fullPage: true })
  const adopt = creative.getByRole("button", { name: "采用这一版…", exact: true })
  await expect(adopt).toBeEnabled()
  await adopt.click()
  await creative.getByRole("button", { name: "确认保存这些修改", exact: true }).click()
  await expect(creative.getByText("所选修改已保存，历史版本与采用记录已保留。", { exact: true })).toBeVisible()
  await panel.getByRole("button", { name: "关闭项目助手", exact: true }).click()
  await expect(editor).toHaveValue(original + "她仍保留了退路。")
  await page.reload()
  await expect(editor).toHaveValue(original + "她仍保留了退路。")
  expect(browserErrors).toEqual([])
})


test("低置信边界单独确认后继续整理，保留草稿语义", async ({ page, projectFactory, openProjectWorkbench, browserErrors }) => {
  const project = await projectFactory({ title: "边界确认 · 临时合成验收" })
  await createDraft(project.id, 1, "待确认的一场", "边界需要核对。")
  await openProjectWorkbench(project, "project-settings")
  await page.getByRole("tab", { name: "高级导入", exact: true }).click()
  const flow = page.locator(".reading-flow")
  await flow.locator("summary").click()
  page.once("dialog", dialog => dialog.accept())
  await flow.getByRole("button", { name: "启用逐场景理解…" }).click()
  await flow.getByLabel("读到第几章").fill("1")
  await flow.getByLabel("本次最多调用模型").fill("5")
  await flow.getByRole("button", { name: "查看理解范围" }).click()
  await flow.getByRole("button", { name: "确认并开始理解" }).click()
  await expect(flow).toContainText("场景边界需要确认", { timeout: 60000 })
  await page.evaluate(() => window.router.navigate("outline", "scenes"))
  const row = page.locator(".scene-workbench-row").first()
  await row.locator('[data-action="select-workbench-scene"]').click()
  const review = page.waitForRequest(request => request.method() === "POST" && request.url().includes("/scene-workbench/review"))
  await page.locator(".scene-detail-context-action").filter({ hasText: "确认边界，继续整理" }).click()
  const confirmation = (await review).postDataJSON()
  expect(confirmation.decision).toBe("review_boundary")
  expect(Object.values(confirmation.boundary_fingerprints)[0]).toMatch(/^[a-f0-9]{64}$/)
  await page.evaluate(() => window.router.navigate("project-settings"))
  await page.getByRole("tab", { name: "高级导入", exact: true }).click()
  await flow.locator("summary").click()
  await flow.getByRole("button", { name: "恢复理解", exact: true }).click()
  await expect(flow).toContainText("所选范围理解已更新", { timeout: 60000 })
  expect((await getLatestDraft(project.id, 1)).content).toBe("边界需要核对。")
  expect(browserErrors).toEqual([])
})

test("世界资料提案从真实理解任务回看，改稿后标为历史", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  const project = await projectFactory({ title: "世界候选 · 临时合成验收" })
  await createDraft(project.id, 1, "相识", "林舟又名小舟。林舟和青竹是盟友。")
  await openProjectWorkbench(project, "project-settings")
  await page.getByRole("tab", { name: "高级导入", exact: true }).click()
  const flow = page.locator(".reading-flow")
  await flow.locator(":scope > summary").click()
  page.once("dialog", dialog => dialog.accept())
  await flow.getByRole("button", { name: "启用逐场景理解…" }).click()
  await flow.getByLabel("读到第几章").fill("1")
  await flow.getByLabel("本次最多调用模型").fill("7")
  await flow.getByRole("button", { name: "查看理解范围" }).click()
  await flow.getByRole("button", { name: "确认并开始理解" }).click()
  await expect(flow).toContainText("所选范围理解已更新", { timeout: 60000 })
  await flow.getByRole("button", { name: "查看世界资料提案" }).click()
  const proposals = flow.getByRole("region", { name: "本次世界资料提案" })
  await proposals.locator("summary").click()
  await expect(proposals).toContainText("候选待采用")
  await expect(proposals).toContainText("林舟 · 别名 小舟")
  await expect(proposals).toContainText("林舟又名小舟。")
  await page.setViewportSize({ width: 390, height: 844 })
  await proposals.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("world-proposals-mobile.png"), fullPage: true })
  await createDraft(project.id, 1, "改稿", "林舟独自离开。")
  await flow.getByRole("button", { name: "查看世界资料提案" }).click()
  await expect(proposals).toContainText("历史或尚未提交")
  expect(browserErrors).toEqual([])
})
