import { test, expect } from "./fixtures.js"
import { createDraft, getLatestDraft } from "./helpers/api-client.js"

test("前瞻与两种真实试改：保存保护、确认、恢复和窄屏", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  const project = await projectFactory({ title: "创作试验 · 临时合成验收" })
  const original = "她接受了旧敌的帮助。窗外的雨还没有停。"
  const initial = "她接受了旧敌的帮助。"
  await createDraft(project.id, 1, "有限合作", initial)
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "1" })))
  await page.getByRole("button", { name: /^打开第 1 章/ }).click()
  const editor = page.locator("#writing-editor")
  await expect(editor).toHaveValue(initial)
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  const panel = page.locator("#project-assistant-panel")
  await panel.getByRole("button", { name: "下一步", exact: true }).click()
  const forecast = panel.getByRole("region", { name: "下一步建议" })
  await expect(forecast.getByText("还没有分析这一处。已有保存资料可以直接查看。")).toBeVisible()
  await editor.dispatchEvent("compositionstart")
  await editor.fill(original)
  await expect(forecast.getByRole("button", { name: "帮我想下一步" })).toBeDisabled()
  await expect(editor).toBeFocused()
  await editor.dispatchEvent("compositionend")
  await page.locator("#btn-autosave").click()
  await expect(forecast.getByRole("button", { name: "帮我想下一步" })).toBeEnabled()
  expect((await getLatestDraft(project.id, 1)).content).toBe(original)
  await forecast.getByRole("button", { name: "帮我想下一步" }).click()
  await expect(forecast.getByRole("heading", { name: "保留一条谨慎合作的退路" })).toBeVisible({ timeout: 45000 })
  await forecast.getByRole("article").filter({ hasText: "保留一条谨慎合作的退路" }).getByRole("button", { name: "加入稍后处理" }).click()
  await expect(forecast.getByRole("button", { name: "确认这一项", exact: true })).toBeEnabled()
  await forecast.getByRole("button", { name: "确认这一项", exact: true }).click()
  await expect(forecast.getByText("这一项已完成。", { exact: true })).toBeVisible()
  expect((await getLatestDraft(project.id, 1)).content).toBe(original)
  await panel.getByRole("button", { name: "试改", exact: true }).click()
  const creative = panel.getByRole("region", { name: "隔离试改" })
  await creative.getByLabel("想解决什么").fill("补足合作的动机，比较保留谨慎与交换条件")
  await creative.getByLabel("必须保留什么").fill("不提前揭露身份")
  await creative.getByRole("button", { name: "开始调查与试改" }).click()
  await expect(creative.getByText("本轮处理完成", { exact: true }).first()).toBeVisible({ timeout: 60000 })
  await expect(creative.locator(".creative-trial-button")).toHaveCount(2)
  expect((await getLatestDraft(project.id, 1)).content).toBe(original)
  await creative.locator(".creative-trial-button").filter({ hasText: "保留谨慎" }).click()
  await expect(creative.getByText("这一版检查通过", { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath("creative-desktop.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("creative-mobile.png"), fullPage: true })
  const adopt = creative.getByRole("button", { name: "采用这一版…", exact: true })
  await expect(adopt).toBeEnabled()
  await adopt.click()
  await creative.getByRole("button", { name: "确认保存这些修改", exact: true }).click()
  await expect(creative.getByText("所选修改已保存，历史版本与采用记录已保留。", { exact: true })).toBeVisible()
  await panel.getByRole("button", { name: "关闭项目助手", exact: true }).click()
  await expect(editor).toHaveValue(original + "她仍保留了退路。")
  await page.reload()
  await expect(editor).toHaveValue(original + "她仍保留了退路。")
  expect(browserErrors).toEqual([])
})
