import { test, expect } from "./fixtures.js"
import { createDraft, createScene, getLatestDraft } from "./helpers/api-client.js"
import { execFileSync } from "node:child_process"

test("作者核对保管和所有权、回读历史依据、比较开锁假设并绑定原稿试改", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  test.slow()
  const project = await projectFactory({ title: "E2E 条件比较 · 临时合成验收" })
  const initial = "她接受了旧敌的帮助。"
  await createDraft(project.id, 2, "核对三簧锁", initial)
  const ids = JSON.parse(execFileSync("../backend/.venv/bin/python", ["-m", "tests.support.scene_state_browser_fixture", project.id], {
    cwd: "../backend", env: { ...process.env, APP_ENV: "test", AUTH_MODE: "local" }, encoding: "utf8",
  }).trim())
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "2" })))
  await page.getByRole("button", { name: /^打开第 2 章/ }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: "本章资料", exact: true }).click()
  const cockpit = page.locator(".scene-cockpit")
  await cockpit.getByRole("tab", { name: "本场", exact: true }).click()
  await cockpit.getByRole("button", { name: /角色可见信息/ }).click()
  const key = cockpit.locator(".scene-lens__objects > li").filter({ has: page.locator("strong", { hasText: "铜钥匙" }) })
  await expect(key).toContainText("所有人")
  await expect(key).toContainText("保管人")
  await expect(key).toContainText("甲")
  await expect(key).toContainText("乙")
  await key.getByRole("button", { name: "查看依据" }).first().click()
  const source = cockpit.getByRole("region", { name: "状态依据" })
  await source.getByRole("button", { name: "查看此前场景依据" }).click()
  await expect(source).toContainText("保管人：乙")
  await source.getByRole("button", { name: "收起依据" }).click()
  const trial = cockpit.locator(".scene-state-trial")
  await trial.locator("summary").click()
  await trial.getByLabel("行动", { exact: true }).selectOption("open_lock")
  await trial.getByLabel("行动人物", { exact: true }).selectOption(ids.jia)
  await trial.getByLabel("钥匙", { exact: true }).selectOption(ids.key)
  await trial.getByLabel("要开启的锁", { exact: true }).selectOption(ids.lock)
  await trial.getByLabel("试改后的保管人", { exact: true }).selectOption(ids.jia)
  await trial.getByLabel("试改月相", { exact: true }).selectOption("full")
  await trial.getByRole("button", { name: "比较原状态与本次假设" }).click()
  await expect(trial).toContainText("原状态 · 明确条件未满足")
  await expect(trial).toContainText("本次假设 · 明确条件已满足")
  await expect(trial).toContainText("当前：未记载；所需：月圆")
  await expect(trial).toContainText("当前：乙；所需：甲")
  await page.screenshot({ path: testInfo.outputPath("state-condition-comparison.png"), fullPage: true })
  const apiRoot = "http://127.0.0.1:" + process.env.BACKEND_PORT + "/api/novels/" + project.id + "/memories/events"
  const before = await (await page.request.get(apiRoot)).json()
  await trial.getByRole("button", { name: "按这个假设发起原稿试改" }).click()
  const panel = page.locator("#project-assistant-panel")
  const creative = panel.getByRole("region", { name: "隔离试改" })
  await expect(creative).toBeVisible()
  await creative.getByLabel("想解决什么").fill("按本次保管人与月圆假设试改，保留所有权与口令知识边界")
  await creative.getByRole("button", { name: "开始调查与试改" }).click()
  await expect(creative.getByText("本轮处理完成", { exact: true }).first()).toBeVisible({ timeout: 60000 })
  expect((await getLatestDraft(project.id, 2)).content).toBe(initial)
  const after = await (await page.request.get(apiRoot)).json()
  expect(after.total).toBe(before.total)
  await creative.locator(".creative-trial-button").filter({ hasText: "保留谨慎" }).click()
  const diff = creative.getByRole("region", { name: "所选试改对照" })
  await diff.getByRole("button", { name: "检查这一版", exact: true }).click()
  await expect(diff.getByText("这一版检查通过", { exact: true })).toBeVisible({ timeout: 60000 })
  await diff.getByRole("button", { name: "采用这一版…", exact: true }).click()
  await diff.getByRole("button", { name: "确认保存这些修改", exact: true }).click()
  await expect(diff.getByText("所选修改已保存，历史版本与采用记录已保留。", { exact: true })).toBeVisible()
  expect((await getLatestDraft(project.id, 2)).content).not.toBe(initial)
  await panel.getByRole("button", { name: "关闭项目助手", exact: true }).click()
  const edited = "她接受了旧敌的帮助，但坚持先核验口令。"
  await createDraft(project.id, 2, "核对三簧锁", edited)
  await page.reload()
  await expect(page.locator("#writing-editor")).toHaveValue(edited)
  await page.getByRole("button", { name: "本章资料", exact: true }).click()
  await cockpit.getByRole("tab", { name: "本场", exact: true }).click()
  await cockpit.getByRole("button", { name: /角色可见信息/ }).click()
  await expect(cockpit).toContainText("暂无可靠记录")
  await expect(cockpit.locator(".scene-lens__object-fields")).toHaveCount(0)
  await cockpit.getByRole("button", { name: "重新整理已有状态记录", exact: true }).click()
  await expect(cockpit.getByRole("status")).toContainText("已按现有事件重新整理；缺少的正文依据和行动条件仍需补充核对。")
  await expect(key).toContainText("所有人")
  await expect(key).toContainText("保管人")
  expect((await (await page.request.get(apiRoot)).json()).total).toBe(before.total)
  await page.getByRole("dialog", { name: "本章资料", exact: true }).getByRole("button", { name: /关闭/ }).click()
  await expect(page.locator("#writing-editor")).toBeEditable()
  expect(browserErrors).toEqual([])
})

test("Scene Lens 状态入口直达试改，带正文与场景预选且零写入", async ({ page, projectFactory, openProjectWorkbench, browserErrors }) => {
  const project = await projectFactory({ title: "状态入口试改 · 临时合成验收" })
  const initial = "她在门前停下了脚步。"
  await createDraft(project.id, 1, "门前", initial)
  await createScene(project.id, {
    scene_index: 0,
    title: "门前驻足",
    goal: "确认她是否进门",
    core_conflict: "进门即认输",
    chapter_ids: ["1"],
  })
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "1" })))
  await page.getByRole("button", { name: /^打开第 1 章/ }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: "本章资料", exact: true }).click()
  const cockpit = page.locator(".scene-cockpit")
  await cockpit.getByRole("tab", { name: "本场", exact: true }).click()
  await cockpit.getByRole("button", { name: /角色可见信息/ }).click()
  const entry = cockpit.getByRole("button", { name: "从本场状态发起试改" })
  await expect(entry).toBeVisible({ timeout: 30000 })
  await entry.click()
  const panel = page.locator("#project-assistant-panel")
  const creative = panel.getByRole("region", { name: "隔离试改" })
  await expect(creative).toBeVisible()
  await expect(page.getByRole("dialog", { name: "本章资料", exact: true })).toHaveCount(0)
  await creative.getByLabel("想解决什么").fill("比较钥匙交接的依据")
  await expect(creative.getByLabel("想解决什么")).toHaveValue("比较钥匙交接的依据")
  expect(await panel.evaluate(element => Boolean(element.closest("[inert]")))).toBe(false)
  await expect(creative.getByRole("checkbox", { name: "当前正文工作稿" })).toBeChecked()
  await expect(creative.getByRole("checkbox", { name: "当前场景安排" })).toBeChecked()
  expect((await getLatestDraft(project.id, 1)).content).toBe(initial)
  await panel.getByRole("button", { name: "关闭项目助手", exact: true }).click()
  await expect(panel).not.toBeVisible()
  await expect(page.locator("#writing-editor")).toBeEditable()
  expect(browserErrors).toEqual([])
})

test("试改期间改稿：就地三方选择后重建并采用，作者中途修改不静默丢失", async ({ page, projectFactory, openProjectWorkbench, browserErrors }, testInfo) => {
  test.slow()
  const project = await projectFactory({ title: "改稿冲突重建 · 临时合成验收" })
  const initial = "她接受了旧敌的帮助。"
  const suffix = "她仍保留了退路。"
  const authorEdit = "她接受了旧敌的帮助，但提出了条件。"
  await createDraft(project.id, 1, "有限合作", initial)
  await openProjectWorkbench(project, "writing")
  await page.evaluate(() => window.router.navigate("writing", null, true, new URLSearchParams({ chapter: "1" })))
  await page.getByRole("button", { name: /^打开第 1 章/ }).click()
  const editor = page.locator("#writing-editor")
  await expect(editor).toHaveValue(initial)
  await page.getByRole("button", { name: "项目助手", exact: true }).click()
  const panel = page.locator("#project-assistant-panel")
  await panel.getByRole("button", { name: "试改", exact: true }).click()
  const creative = panel.getByRole("region", { name: "隔离试改" })
  await creative.getByLabel("想解决什么").fill("补足合作的动机，比较保留谨慎与交换条件")
  await creative.getByLabel("必须保留什么").fill("不提前揭露身份")
  await creative.getByRole("checkbox", { name: "当前正文工作稿" }).check()
  await creative.getByRole("button", { name: "开始调查与试改" }).click()
  await expect(creative.getByText("本轮处理完成", { exact: true }).first()).toBeVisible({ timeout: 60000 })
  expect((await getLatestDraft(project.id, 1)).content).toBe(initial)
  await creative.locator(".creative-trial-button").filter({ hasText: "保留谨慎" }).click()
  const diff = creative.getByRole("region", { name: "所选试改对照" })
  await expect(diff.getByText("这一版检查通过", { exact: true })).toBeVisible()
  await expect(diff.getByText("字段级改动", { exact: false })).toBeVisible()
  await expect(diff.getByText("状态影响", { exact: false })).toBeVisible()
  await createDraft(project.id, 1, "有限合作", authorEdit)
  await creative.locator(".creative-trial-button").filter({ hasText: "保留谨慎" }).first().click()
  await expect(diff.getByText("参考资料或目标已变化，旧试改不能直接采用。")).toBeVisible()
  await diff.getByRole("button", { name: "基于当前稿重建试改" }).click()
  const conflictPanel = diff.getByRole("region", { name: "重建冲突处理" })
  await expect(conflictPanel.getByText("当前稿与试改改了同一批字段")).toBeVisible()
  expect((await getLatestDraft(project.id, 1)).content).toBe(authorEdit)
  await page.screenshot({ path: testInfo.outputPath("rebase-conflict.png"), fullPage: true })
  await conflictPanel.getByRole("radio", { name: /采用试改/ }).check()
  await conflictPanel.getByRole("button", { name: "按以上选择重建" }).click()
  await expect(diff.locator("h4")).toContainText("重建试改", { timeout: 30000 })
  await expect(diff.getByText("参考资料或目标已变化，旧试改不能直接采用。")).toHaveCount(0)
  await diff.getByRole("button", { name: "检查这一版", exact: true }).click()
  await expect(diff.getByText("这一版检查通过", { exact: true })).toBeVisible({ timeout: 60000 })
  const adopt = diff.getByRole("button", { name: "采用这一版…", exact: true })
  await expect(adopt).toBeEnabled()
  await adopt.click()
  await diff.getByRole("button", { name: "确认保存这些修改", exact: true }).click()
  await expect(diff.getByText("所选修改已保存，历史版本与采用记录已保留。", { exact: true })).toBeVisible()
  expect((await getLatestDraft(project.id, 1)).content).toBe(initial + suffix)
  await page.screenshot({ path: testInfo.outputPath("rebase-merged.png"), fullPage: true })
  expect(browserErrors).toEqual([])
})
