import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { test, expect } from "./fixtures.js"
import { API_BASE } from "./helpers/api-client.js"
import { expectNoPageOverflow } from "./helpers/responsive.js"
import { openWorkbench, reloadWorkbench } from "./helpers/workbench.js"

const sample = JSON.parse(readFileSync(new URL("./fixtures/unified-map.json", import.meta.url), "utf8"))
const png = fileURLToPath(new URL("./fixtures/unified-map.png", import.meta.url))
const headers = { "X-Requested-With": "XMLHttpRequest" }

async function createMap(request, projectId) {
  const created = await request.post(API_BASE + "/world/map-atlas/" + projectId + "/nodes", { headers, data: { title: "河谷地图", level: "region" } })
  expect(created.ok()).toBeTruthy()
  const node = await created.json()
  const saved = await request.post(API_BASE + "/world/map-atlas/" + projectId + "/nodes/" + node.id + "/revisions", { headers, data: { base_revision_id: node.current_revision_id, document: sample } })
  expect(saved.ok()).toBeTruthy()
  return { ...node, current_revision_id: (await saved.json()).id }
}

test("无需图片模型即可创建、编辑保存并进入城市子图", async ({ page, request, projectFactory }, testInfo) => {
  const project = await projectFactory({ title: "统一地图手动闭环" })
  await openWorkbench(page, project, "map")
  await page.getByRole("button", { name: "新建地图", exact: true }).click()
  const form = page.getByRole("form", { name: "新建空间地图" })
  await form.getByLabel("地图名称").fill("河谷地图")
  const createdResponse = page.waitForResponse(response => response.url().endsWith("/nodes") && response.request().method() === "POST")
  await form.getByRole("button", { name: "建立地图" }).click()
  const node = await (await createdResponse).json()
  await expect(page.locator(".map-editor")).toBeVisible()
  const saved = await request.post(API_BASE + "/world/map-atlas/" + project.id + "/nodes/" + node.id + "/revisions", { headers, data: { base_revision_id: node.current_revision_id, document: sample } })
  expect(saved.ok()).toBeTruthy()
  await reloadWorkbench(page, "map")
  await expect(page.locator(".map-feature")).toHaveCount(15)
  await page.locator(".map-feature").filter({ has: page.locator("text", { hasText: "临江城" }) }).click()
  await page.getByRole("button", { name: "向右移动", exact: true }).click()
  await page.getByRole("button", { name: "保存地图", exact: true }).click()
  await expect(page.locator(".map-save-status")).toHaveText("已保存到服务端")
  await reloadWorkbench(page, "map")
  const state = await (await request.get(API_BASE + "/world/map-atlas/" + project.id + "/nodes/" + node.id + "/map")).json()
  expect(state.revision.document.features.find(feature => feature.id === "place0").points[0].x).toBe(150)
  await page.getByRole("button", { name: "为此地点创建城市图" }).click()
  await page.getByRole("button", { name: "保存地图", exact: true }).click()
  await expect(page.locator(".map-save-status")).toHaveText("已保存到服务端")
  await page.screenshot({ path: testInfo.outputPath("unified-map-desktop.png"), fullPage: true })
  const lightFill = await page.locator('.map-paper').evaluate(element => getComputedStyle(element).fill)
  await page.getByRole('radio', { name: '切换到深色', exact: true }).click()
  await expect.poll(() => page.locator('.map-paper').evaluate(element => getComputedStyle(element).fill)).not.toBe(lightFill)
  await page.locator('.map-scroll').screenshot({ path: testInfo.outputPath('unified-map-dark.png') })
  await page.getByRole('radio', { name: '切换到浅色', exact: true }).click()
  await page.locator('.map-scroll').screenshot({ path: testInfo.outputPath('unified-map-canvas.png') })
  await page.getByRole("button", { name: "进入子图", exact: true }).click()
  await expect(page.locator(".atlas-page-header h2")).toHaveText("临江城")
  await page.reload()
  await expect(page.locator(".atlas-page-header h2")).toHaveText("临江城")
  await page.setViewportSize({ width: 390, height: 844 })
  await expectNoPageOverflow(page)
  await page.screenshot({ path: testInfo.outputPath("unified-map-mobile.png"), fullPage: true })
})

test("旧图片上传采用后可校准到同一画布，阅读预览保守排除隐藏内容", async ({ page, request, projectFactory }, testInfo) => {
  const project = await projectFactory({ title: "统一地图图片与阅读预览" })
  const node = await createMap(request, project.id)
  await openWorkbench(page, project, "map")
  await expect(page.locator(".map-feature")).toHaveCount(15)
  const previewPromise = page.waitForResponse(response => response.url().includes("/reader-preview?"))
  await page.getByRole("button", { name: "预览读者所见" }).click()
  const projection = await (await previewPromise).json()
  expect(JSON.stringify(projection)).not.toContain("藏风谷")
  expect(JSON.stringify(projection)).not.toContain("北岭遗址")
  expect(JSON.stringify(projection)).not.toContain("conflict")
  await expect(page.locator(".map-edit-grid")).toHaveCount(0)
  await page.getByRole("button", { name: "回到作者视图" }).click()
  const constraints = page.locator("details").filter({ has: page.locator("summary", { hasText: "空间关系" }) }).first()
  await constraints.locator("summary").click()
  await constraints.locator("li").getByRole("button", { name: "移出", exact: true }).click()
  await page.getByRole("button", { name: "保存地图", exact: true }).click()
  await expect(page.locator(".map-save-status")).toHaveText("已保存到服务端")
  await page.getByRole("button", { name: "上传地图", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "上传地图图片" })
  await dialog.locator('input[type="file"]').setInputFiles(png)
  await dialog.getByLabel("放到哪张地图下").selectOption(node.id)
  await dialog.getByRole("button", { name: "上传为候选" }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole("button", { name: "加入地图册", exact: true }).click()
  await expect(page.getByRole("button", { name: "加入地图册", exact: true })).toHaveCount(0)
  await page.getByRole("tab", { name: /我的地图册/ }).click()
  await expect(page.locator(".map-editor")).toBeVisible()
  const controls = page.locator(".map-image-controls")
  await controls.locator("summary").first().click()
  const atlas = await (await request.get(API_BASE + "/world/map-atlas/" + project.id + "/atlas")).json()
  const pageId = atlas.nodes[0].pages[0].id
  await controls.getByLabel("已采用图片").selectOption(pageId)
  await controls.getByRole("combobox", { name: "用途", exact: true }).selectOption("background")
  const selectors = controls.locator(".map-inline-form").nth(1).locator("select")
  await selectors.nth(0).selectOption("place0")
  await selectors.nth(1).selectOption("place1")
  await selectors.nth(2).selectOption("place2")
  const scale = 728 / 840
  for (const [index, [x, y]] of [[140, 420], [350, 120], [730, 160]].entries()) {
    await controls.getByLabel("锚点" + (index + 1) + "横向比例").fill(String((20 + x * scale) / 1024))
    await controls.getByLabel("锚点" + (index + 1) + "纵向比例").fill(String((20 + (y + 10) * scale) / 768))
  }
  await controls.getByLabel("已人工核对整张图片，最早在第几章开始时展示").fill("8")
  await controls.getByRole("button", { name: "预览图片设置" }).click()
  await expect(page.locator(".map-canvas image")).toHaveCount(1)
  await page.getByRole("button", { name: "保存地图", exact: true }).click()
  await expect(page.locator(".map-save-status")).toHaveText("已保存到服务端")
  await expect(page.locator(".map-canvas image")).toHaveAttribute("href", /blob:/)
  await page.screenshot({ path: testInfo.outputPath("unified-map-background.png"), fullPage: true })
  await page.getByRole("button", { name: "预览读者所见" }).click()
  await expect(page.locator(".map-canvas image")).toHaveCount(0)
  await page.getByLabel("阅读预览章节").fill("8")
  await page.getByRole("button", { name: "更新阅读预览" }).click()
  await expect(page.locator(".map-canvas image")).toHaveCount(1)
  await page.getByRole("button", { name: "回到作者视图" }).click()
  await page.getByRole("button", { name: "向右移动", exact: true }).click()
  await expect(page.locator(".map-canvas image")).toHaveCount(0)
  await expect(controls).toContainText("待复核，已退出叠加")
})
