import { test, expect } from './fixtures.js'
import { createDraft, getLatestDraft } from './helpers/api-client.js'
import { openWorkbench, waitWritingReady } from './helpers/workbench.js'
import { expectActionReachable, expectResponsiveLayout, runResponsiveMatrix } from './helpers/responsive.js'
import { mockRpApis, journeyId } from './helpers/rp-fixture.js'
import { atlasPage, mockAtlas, PNG } from './helpers/atlas-fixture.js'

test.use({ isMobile: true, hasTouch: true, viewport: { width: 390, height: 844 } })
test.describe('移动核心流程', () => {

async function openChapter(page, project) {
  await createDraft(project.id, 1, '跨屏幕继续创作', '甲😀乙丙\n'.repeat(30))
  await openWorkbench(page, project, 'writing')
  await page.evaluate(() => window.router.navigate('writing', null, true, new URLSearchParams({ chapter_index: '1' })))
  await waitWritingReady(page, { editor: true })
  return page.getByRole('textbox', { name: '章节正文', exact: true })
}

test('完整编辑器跨尺寸保留正文、选区、资料草稿和桌面侧栏偏好', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '跨尺寸创作与恢复' })
  await page.setViewportSize({ width: 1440, height: 900 })
  const editor = await openChapter(page, project)
  await page.getByRole('button', { name: '章节', exact: true }).click()
  const preference = await page.evaluate(id => sessionStorage.getItem(`workspace-rail:${id}:writing:chapters`), project.id)
  await editor.fill('甲😀乙丙\n待保存正文')
  await page.getByRole('button', { name: '保存工作稿', exact: true }).click()
  await expect(page.locator('#writing-save-status')).toHaveText('已保存到工作稿')
  await editor.evaluate(element => { element.focus(); element.setSelectionRange(1, 4); element.dispatchEvent(new Event('select', { bubbles: true })) })
  await page.getByRole('button', { name: '批注选中内容', exact: true }).click()
  const note = page.getByLabel('希望怎么修改？')
  await note.fill('尚未保存的批注草稿')
  for (const viewport of [{ width: 1024, height: 768 }, { width: 390, height: 844 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(viewport)
    await expect(editor).toHaveValue('甲😀乙丙\n待保存正文')
    await expect.poll(() => editor.evaluate(element => [element.selectionStart, element.selectionEnd])).toEqual([1, 4])
    const trigger = page.getByRole('button', { name: '本章资料', exact: true })
    if (await trigger.getAttribute('aria-expanded') === 'false') await trigger.click()
    const dialog = page.getByRole('dialog', { name: '本章资料', exact: true })
    await expect(dialog).toBeVisible()
    await expect(note).toHaveValue('尚未保存的批注草稿')
    const close = dialog.getByRole('button', { name: '关闭本章资料' })
    await expectActionReachable(close)
    await close.click()
    await expect(dialog).toBeHidden()
    await expect(trigger).toBeFocused()
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await expect(page.getByRole('button', { name: '章节', exact: true })).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(id => sessionStorage.getItem(`workspace-rail:${id}:writing:chapters`), project.id)).toBe(preference)
  expect((await getLatestDraft(project.id, 1)).content).toBe('甲😀乙丙\n待保存正文')
})

test('手机保存失败保留正文，重试后实际保存并可刷新恢复', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '窄屏保存保护' })
  const editor = await openChapter(page, project)
  const failSave = route => route.request().method() === 'PUT' ? route.fulfill({ status: 503, json: { detail: '测试网络暂时不可用' } }) : route.fallback()
  await page.route('**/api/writing/drafts/*?*', failSave)
  await editor.fill('网络失败时仍保留的正文')
  await page.getByRole('button', { name: '保存工作稿', exact: true }).click()
  await expect(page.locator('#writing-save-status')).toContainText('保存失败')
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(editor).toHaveValue('网络失败时仍保留的正文')
  await page.unroute('**/api/writing/drafts/*?*', failSave)
  await page.getByRole('button', { name: '保存工作稿', exact: true }).click()
  await expect(page.locator('#writing-save-status')).toHaveText('已保存到工作稿')
  await page.reload()
  await expect(editor).toHaveValue('网络失败时仍保留的正文')
})

test('地图标注可触控点选、取消、微调并按版本保存，失败不丢调整', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '触控地图标注' })
  const annotation = { id: 'annotation-1', label: '北门', position_x: .25, position_y: .75, updated_at: '2026-09-01T00:00:00Z' }
  const map = atlasPage('page-touch', { review_status: 'adopted', annotations: [annotation, { id: 'bound-1', label: '跟随地点', position_x: .1, position_y: .1, bound_feature_id: 'feature-1', updated_at: annotation.updated_at }] })
  await mockAtlas(page, { adopted: [map] })
  let failed = true
  const writes = []
  await page.route('**/api/world/map-atlas/**/annotations/annotation-1', route => {
    writes.push(route.request().postDataJSON())
    return failed ? route.fulfill({ status: 409, json: { detail: 'stale annotation' } }) : route.fulfill({ json: { ...annotation, ...writes.at(-1), updated_at: '2026-09-01T00:00:01Z' } })
  })
  await openWorkbench(page, project, 'map')
  await page.getByText('调整标注位置', { exact: true }).click()
  const picker = page.getByRole('combobox', { name: '地图标注', exact: true })
  await expect(picker.locator('option[value="bound-1"]')).toHaveAttribute('disabled', '')
  await picker.evaluate(element => { element.value = 'bound-1'; element.dispatchEvent(new Event('change', { bubbles: true })) })
  await expect(page.getByRole('button', { name: '保存标注位置' })).toHaveCount(0)
  expect(writes).toHaveLength(0)
  await picker.selectOption('annotation-1')
  await page.locator('.atlas-image-canvas').click({ position: { x: 30, y: 30 } })
  await page.getByRole('button', { name: '取消调整' }).click()
  expect(writes).toHaveLength(0)
  await picker.selectOption('annotation-1')
  await page.getByRole('button', { name: '标注向右移动' }).tap()
  const hotspot = page.getByRole('button', { name: '北门', exact: true })
  await hotspot.focus()
  for (const key of ['Enter', 'Space']) {
    await page.keyboard.press(key)
    await expect(hotspot).toHaveAttribute('style', /left: 26%/)
    await expect(hotspot).toHaveAttribute('style', /top: 75%/)
    expect(writes).toHaveLength(0)
  }
  await page.setViewportSize({ width: 844, height: 390 })
  const save = page.getByRole('button', { name: '保存标注位置' })
  await save.click()
  await expect(page.getByRole('alert').filter({ hasText: '位置调整仍保留' })).toBeVisible()
  expect(writes[0]).toEqual({ position_x: .26, position_y: .75, expected_updated_at: annotation.updated_at })
  failed = false
  await page.getByRole('button', { name: '取消调整' }).click()
  annotation.updated_at = '2026-09-01T00:00:01Z'
  await page.reload()
  await page.getByText('调整标注位置', { exact: true }).click()
  await picker.selectOption('annotation-1')
  await page.getByRole('button', { name: '标注向右移动' }).click()
  await save.click()
  await expect(page.getByText('标注位置已保存', { exact: true })).toBeVisible()
  expect(writes).toHaveLength(2)
  await expect(page.getByRole('button', { name: '取消调整' })).toHaveCount(0)
})

test('地图上传和移出前确认未保存位置，取消与失败保留两份草稿', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '换图保护未保存标注' })
  const annotation = { id: 'annotation-1', label: '北门', position_x: .25, position_y: .75, updated_at: '2026-09-01T00:00:00Z' }
  await mockAtlas(page, { adopted: [atlasPage('page-upload-guard', { review_status: 'adopted', annotations: [annotation] })] })
  let uploads = 0
  await page.route('**/api/world/map-atlas/**/pages/upload', route => {
    uploads += 1
    return route.fulfill({ status: 503, json: { detail: '测试上传失败' } })
  })
  await openWorkbench(page, project, 'map')
  await page.getByText('调整标注位置', { exact: true }).click()
  await page.getByRole('combobox', { name: '地图标注', exact: true }).selectOption('annotation-1')
  await page.getByRole('button', { name: '标注向右移动' }).click()
  const hotspot = page.locator('.atlas-annotation').filter({ hasText: '北门' })
  await page.getByRole('button', { name: '移出地图册', exact: true }).click()
  const leave = page.locator('#modal-overlay')
  await expect(leave).toContainText('标注位置尚未保存')
  await leave.getByRole('button', { name: '取消', exact: true }).click()
  await expect(hotspot).toHaveAttribute('style', /left: 26%/)
  await page.getByText('图片与底图', { exact: true }).click()
  await page.getByRole('button', { name: '上传地图图片', exact: true }).click()
  const upload = page.getByRole('dialog', { name: '上传地图图片', exact: true })
  await upload.getByLabel('图片（PNG 或 JPEG，最大 50MB）').setInputFiles({ name: 'synthetic-map.png', mimeType: 'image/png', buffer: PNG })
  await upload.getByLabel('地图名称', { exact: true }).fill('尚未上传的码头图')
  await upload.getByRole('button', { name: '上传为候选' }).click()
  await expect(leave).toContainText('标注位置尚未保存')
  await leave.getByRole('button', { name: '取消', exact: true }).click()
  expect(uploads).toBe(0)
  await expect(upload.getByLabel('地图名称', { exact: true })).toHaveValue('尚未上传的码头图')
  await upload.getByRole('button', { name: '上传为候选' }).click()
  await leave.getByRole('button', { name: '确认离开', exact: true }).click()
  await expect(upload.getByRole('alert')).toContainText('测试上传失败')
  expect(uploads).toBe(1)
  await expect(hotspot).toHaveAttribute('style', /left: 26%/)
  await expect(upload.getByLabel('地图名称', { exact: true })).toHaveValue('尚未上传的码头图')
  expect(await upload.locator('input[type="file"]').evaluate(element => element.files[0]?.name)).toBe('synthetic-map.png')
})

test('移动导航与菜单末项在矮屏可命中并正确返回焦点', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '窄屏导航' })
  await openWorkbench(page, project, 'world', 'bible')
  await page.setViewportSize({ width: 390, height: 320 })
  const all = page.locator('.sidebar-mobile-nav').getByRole('button', { name: '全部', exact: true })
  await all.click()
  const menu = page.getByRole('dialog', { name: '全部功能', exact: true })
  await expectActionReachable(menu.getByRole('button', { name: /作品偏好/ }))
  await page.keyboard.press('Escape')
  await expect(menu).toBeHidden()
  await expect(all).toBeFocused()
  await all.click()
  await menu.getByRole('button', { name: /作品偏好/ }).click()
  await expect(page).toHaveURL(/project-settings/)
  await expectResponsiveLayout(page)
})

test('手机地图候选保留蒙版上传、修改说明和确认入口', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '手机局部图片修改' })
  await mockAtlas(page, { candidate: atlasPage('mask-candidate') })
  await openWorkbench(page, project, 'map')
  await page.getByText('AI 修改 / 重生成', { exact: true }).click()
  const mask = page.getByLabel('局部修改蒙版（PNG）')
  await expect(mask).toBeVisible()
  await mask.setInputFiles({ name: 'synthetic-mask.png', mimeType: 'image/png', buffer: PNG })
  const instruction = page.getByPlaceholder('描述希望修改的画面；重生成可留空')
  await instruction.fill('保留港口，只调整北侧码头')
  await page.setViewportSize({ width: 844, height: 390 })
  await expect(instruction).toHaveValue('保留港口，只调整北侧码头')
  expect(await mask.evaluate(element => element.files[0]?.name)).toBe('synthetic-mask.png')
  await runResponsiveMatrix(page, async () => {
    await expect(mask).toBeVisible()
    await expect(instruction).toHaveValue('保留港口，只调整北侧码头')
    await expectActionReachable(page.getByRole('button', { name: '按说明修改', exact: true }))
    await expectResponsiveLayout(page)
  })
})

test('RP跨尺寸与刷新保留故事、当前发展和输入，矮屏回顾与菜单可达', async ({ page }) => {
  const journey = await mockRpApis(page)
  journey.messages.find(item => item.id === 'a1').content = '钟楼的铜门在海风里缓缓打开。\n\n'.repeat(70)
  journey.messages.find(item => item.id === 'a3').content += '\n\n' + '新墨迹映出城里的另一条街道。\n\n'.repeat(70)
  await page.goto(`/#interaction/${journeyId}`)
  const composer = page.locator('.rp-composer textarea')
  await expect(composer).toBeVisible()
  await composer.fill('待发送的行动不会因屏幕变化消失')
  const text = page.locator('[data-rp-message-id="a3"]')
  await expect(text).toContainText('墨迹')
  const anchor = page.locator('[data-rp-message-id="a2"]')
  await anchor.evaluate(element => element.scrollIntoView({ block: 'start' }))
  const anchorVisible = () => anchor.evaluate(element => {
    const pane = element.closest('.rp-story-scroll').getBoundingClientRect(), rect = element.getBoundingClientRect()
    return rect.bottom > pane.top && rect.top < pane.bottom
  })
  await expect.poll(anchorVisible).toBe(true)
  await expect.poll(() => page.evaluate(id => JSON.parse(sessionStorage.getItem(`novel_rp_scroll:${id}`) || 'null')?.anchorId, journeyId)).toBe('a2')
  for (const viewport of [{ width: 768, height: 900 }, { width: 844, height: 390 }, { width: 390, height: 320 }, { width: 390, height: 844 }]) {
    await page.setViewportSize(viewport)
    await expect(composer).toHaveValue('待发送的行动不会因屏幕变化消失')
    await expect(text).toContainText('墨迹')
    await expect.poll(anchorVisible).toBe(true)
    await expectActionReachable(page.getByRole('button', { name: '回顾', exact: true }))
  }
  await page.reload()
  await expect(composer).toHaveValue('待发送的行动不会因屏幕变化消失')
  await expect(text).toContainText('墨迹')
  await expect.poll(anchorVisible).toBe(true)
  await page.getByRole('button', { name: '回顾', exact: true }).click()
  const overview = page.getByLabel('当前回顾', { exact: true })
  await expect(overview).toBeVisible()
  await expectActionReachable(overview.getByRole('button', { name: '关闭当前回顾' }))
  await overview.getByRole('button', { name: '关闭当前回顾' }).click()
  await expectResponsiveLayout(page)
})

test('RP长回复中段阅读位置在高度、宽度变化和刷新后保留', async ({ page }) => {
  const journey = await mockRpApis(page)
  journey.messages.find(item => item.id === 'a1').content = Array.from({ length: 90 }, (_, index) => `第${index + 1}段：铜门之后的长廊仍然传来海潮声，修表师继续向前寻找旧钟的来源。`).join('\n\n')
  journey.messages.find(item => item.id === 'a3').content += '\n\n' + '后续故事。\n\n'.repeat(90)
  await page.goto(`/#interaction/${journeyId}`)
  const paragraphs = page.locator('[data-rp-message-id="a1"] .rp-message__text > p')
  await expect(paragraphs).toHaveCount(90)
  await paragraphs.nth(44).evaluate(element => element.scrollIntoView({ block: 'center', behavior: 'instant' }))
  const savedPosition = () => page.evaluate(id => JSON.parse(sessionStorage.getItem(`novel_rp_scroll:${id}`) || 'null'), journeyId)
  await expect.poll(async () => (await savedPosition())?.anchorId).toBe('a1')
  const saved = await savedPosition()
  expect(saved.blockIndex).toBeGreaterThan(0)
  const anchor = paragraphs.nth(saved.blockIndex)
  const anchorOffset = () => anchor.evaluate(element => element.getBoundingClientRect().top - element.closest('.rp-story-scroll').getBoundingClientRect().top)
  for (const viewport of [{ width: 390, height: 640 }, { width: 768, height: 900 }, { width: 844, height: 390 }, { width: 390, height: 844 }]) {
    await page.setViewportSize(viewport)
    await expect.poll(async () => Math.abs(await anchorOffset() - saved.anchorOffset)).toBeLessThan(2)
    await expect.poll(async () => (await savedPosition())?.blockIndex).toBe(saved.blockIndex)
  }
  await page.reload()
  await expect(paragraphs).toHaveCount(90)
  await expect.poll(async () => Math.abs(await anchorOffset() - saved.anchorOffset)).toBeLessThan(2)
})

test('登录表单、协议链接和错误输入在屏幕矩阵中保持可操作', async ({ page }) => {
  await page.route('**/api/auth/config', route => route.fulfill({ json: { auth_mode: 'public', email_enabled: true, wechat_enabled: false, terms_url: '/legal/terms', privacy_url: '/legal/privacy' } }))
  await page.route('**/api/auth/me', route => route.fulfill({ status: 401, json: { detail: 'Authentication required' } }))
  await page.route('**/api/auth/email/request-code', route => route.fulfill({ status: 422, json: { detail: '邮箱格式不正确' } }))
  await page.goto('/')
  await page.getByRole('button', { name: /我是作家/ }).click()
  const email = page.getByLabel('邮箱', { exact: true })
  await expect(email).toBeVisible()
  await email.fill('not-an-email')
  await page.getByRole('button', { name: /发送验证码/ }).click()
  await expect(page.getByRole('alert')).toContainText('邮箱格式不正确')
  await runResponsiveMatrix(page, async () => {
    await expect(email).toHaveValue('not-an-email')
    await expect(page.getByRole('alert')).toContainText('邮箱格式不正确')
    await expect(page.getByRole('link', { name: '用户协议', exact: true })).toHaveAttribute('href', '/legal/terms')
    await expectActionReachable(page.getByRole('link', { name: '隐私政策', exact: true }))
    await expectActionReachable(page.getByRole('button', { name: /发送验证码/ }))
  })
})

test('主要断点两侧、缩放重排与两倍字体保留正文及保存入口', async ({ page, projectFactory }) => {
  const project = await projectFactory({ title: '缩放与连续窗口调整' })
  const editor = await openChapter(page, project)
  const content = await editor.inputValue()
  const widths = [759, 760, 761, 899, 900, 901, 1099, 1100, 1101, 1149, 1150, 1151, 640, 320]
  await runResponsiveMatrix(page, async () => {
    await expect(editor).toHaveValue(content)
    await expectResponsiveLayout(page)
    await expectActionReachable(page.getByRole('button', { name: '保存工作稿', exact: true }))
  }, widths.map(width => ({ width, height: 800 })))
  await page.evaluate(() => {
    const elements = Array.from(document.querySelectorAll('#workspace-content button, #workspace-content input, #workspace-content textarea, #workspace-content summary, #workspace-content h1, #workspace-content h2'))
    const sizes = elements.map(element => [element, parseFloat(getComputedStyle(element).fontSize) * 2])
    for (const [element, size] of sizes) element.style.setProperty('font-size', `${size}px`, 'important')
  })
  await expectResponsiveLayout(page)
  await expectActionReachable(page.getByRole('button', { name: '保存工作稿', exact: true }))
})

test('公共演示阅读器跨屏幕可切章且不请求作者工作稿或版本', async ({ page }) => {
  const id = '00000000-0000-4000-8000-000000000077'
  const reads = []
  await page.route('**/api/**', route => {
    const request = route.request(), url = new URL(request.url()), path = url.pathname
    if (path.endsWith('.js')) return route.fallback()
    reads.push({ path, method: request.method() })
    if (path === '/api/auth/config') return route.fulfill({ json: { auth_mode: 'local', demo: { enabled: true, project_id: id, title: '只读演示作品', version: 1 } } })
    if (path === '/api/health') return route.fulfill({ json: { status: 'ok' } })
    if (path === '/api/writing/chapters') return route.fulfill({ json: { chapter_indices: [1, 2], chapters: [1, 2].map(chapter_index => ({ chapter_index, title: `正式正文第${chapter_index}章`, word_count: 8 })) } })
    const chapter = path.match(/^\/api\/writing\/chapters\/([12])\/draft$/)
    if (chapter) return route.fulfill({ json: { chapter_index: Number(chapter[1]), title: `正式正文第${chapter[1]}章`, content: `第${chapter[1]}章的公开正文` } })
    if (path === `/api/projects/${id}`) return route.fulfill({ json: { id, title: '只读演示作品', mode: 'author' } })
    return route.fulfill({ status: 403, json: { detail: '未开放的作者接口' } })
  })
  await page.goto(`/?demo=1#workbench/${id}/writing?chapter_index=1`)
  const reader = page.locator('.public-demo-reader')
  await expect(reader).toContainText('第1章的公开正文')
  await runResponsiveMatrix(page, async () => {
    const next = reader.getByRole('button', { name: /第 2 章/ })
    await expectActionReachable(next)
    await next.click()
    await expect(reader).toContainText('第2章的公开正文')
    await reader.getByRole('button', { name: /第 1 章/ }).click()
    await expectResponsiveLayout(page)
  })
  expect(reads.every(read => read.method === 'GET')).toBe(true)
  expect(reads.some(read => /\/versions|\/writing\/drafts|\/scene/.test(read.path))).toBe(false)
  await expect(page.getByRole('button', { name: '保存工作稿', exact: true })).toHaveCount(0)
})
})
