<template>
  <span v-if="value == null">未填写</span>
  <p v-else-if="typeof value !== 'object'" class="assistant-value-text">{{ formatted }}</p>
  <ul v-else-if="Array.isArray(value)" class="assistant-value-list"><li v-for="(item, index) in value" :key="index"><AssistantValue :value="item" :field-name="fieldName" /></li></ul>
  <dl v-else class="assistant-value-fields"><template v-for="(item, key) in visibleFields" :key="key"><dt>{{ labels[key] || key }}</dt><dd><AssistantValue :value="item" :field-name="key" /></dd></template></dl>
</template>
<script setup>
import { computed } from "vue"
const props = defineProps({ value: { default: null }, fieldName: { type: String, default: "" } })
const hiddenFields = new Set(["page_meta_json", "linked_asset_refs_json", "sort_order", "template_key", "template_version", "provenance_meta", "provenance_json"])
const labels = { name: "名称", title: "标题", summary: "概述", public_info: "公开设定", hidden_truth: "隐藏设定", content_json: "详细资料", importance: "重要程度", importance_level: "重要程度", reveal_level: "可见范围", entity_type: "类型", note: "备注", due_date: "日期", level: "地图范围", free_text: "正文", sections_json: "资料段落", goal: "场景目标", core_conflict: "主要冲突", emotional_beat: "情绪变化", must_happen: "需要发生", must_not_happen: "需要避免", scene_index: "场景顺序", parent: "上级地图", location: "关联地点", content: "正文", creative_core: "创作核心", premise: "故事前提", tone_and_reader_promise: "基调与阅读期待", story_engine: "故事动力", ending_direction: "结局方向", outline_markdown: "总纲正文", major_storylines: "主要故事线", narrative_function: "叙事作用", trajectory: "发展轨迹", intersections: "交汇点", resolution_direction: "收束方向", macro_movements: "故事阶段", story_state_change: "局面变化", advanced_storylines: "推进的故事线", open_decisions: "待决定事项", question: "问题", why_it_matters: "影响", options: "备选方案", personality: "性格", current_goal: "当前目标", current_state: "当前状态", current_emotion: "当前情绪", knowledge: "掌握的信息", misconceptions: "误解", voice_style: "语言风格", behavior_constraints: "行为约束", relationship_state: "关系状态", author_notes: "作者备注", desires: "欲望", fears: "恐惧", beliefs: "信念", pov_character: "视角人物", source: "来源", target: "关联对象", aliases: "别名", alias: "别名", alias_type: "别名类型", relation: "关系", relation_kind: "关系类别", description: "说明", strength: "关系强度" }
Object.assign(labels, { action: "讨论步骤", round_no: "轮次", depth: "深化程度", decisions: "讨论决定", disposition: "处理选择", payload: "建议内容", entity: "世界对象", operation: "处理方式", world_state: "世界状态", world_core: "世界核心", decision_state: "创作决定", text: "内容", threads: "剧情线", arcs: "篇章", scenes: "场景", result: "结果", reuse_judgments: "与已有规划的关系", story_outline_conflict: "与总纲的分歧", author_decisions: "待你决定", information_movements: "信息推进", information_subject: "线索或秘密", surface_understanding: "表层理解", hidden_content: "隐藏内容", nodes: "铺垫与揭示节点", kind: "节点用途", chapter_hint: "建议章节", trigger: "触发条件", effect: "预期影响", basis: "依据", uncertain_fields: "尚不确定", visible_goal: "公开目标", start_chapter: "开始章节", end_chapter: "结束章节", planned_payoff_chapter: "预计回收章节", current_stage: "当前阶段", thread_type: "剧情线类型", reader_known_state: "读者当前理解", author_known_state: "作者掌握的真相", arc_goal: "篇章目标", main_opposition: "主要阻力", entry_hook: "开篇悬念", midpoint_turn: "中段转折", climax: "高潮", next_hook: "下一阶段悬念", planned_start_chapter: "计划开始章节", planned_end_chapter: "计划结束章节", judgment: "建议", alternatives: "可选方向", reason: "原因", narrative_tag: "叙事作用" })
const enums = { core_entity: "世界对象", entity_relation: "关系", world_bible_page: "世界资料页", entity_aliases: "别名", alias: "别名", include: "纳入提案", open: "待决定", rejected: "暂不采用", locked: "保留这项决定", consolidate: "汇总", expand: "展开", connect: "连接", pressure: "检验后果", candidate: "候选", instance: "具体化", create: "新增", promote: "采用既有候选", existing_ref: "引用已有内容", fill_empty: "补齐空白", proposed: "待你审阅的提案", no_change: "暂无需修改", needs_author_decision: "需要你先作决定", seed: "埋设", reinforce: "强化", payoff: "回收", partial_reveal: "部分揭示", full_reveal: "完整揭示", reuse: "沿用", revise: "修订", not_relevant: "本次无需使用", main: "主线", sub: "支线",  region: "区域", city: "城市", district: "街区", street: "街道", character: "人物", location: "地点", faction: "势力", item: "物品", event: "事件", rule: "规则", background: "背景", author_only: "作者可见", core: "核心", important: "重要", normal: "普通", draft: "工作稿", state: "状态", social: "社会关系", spatial: "空间关系", causal: "因果关系", temporal: "时间关系", epistemic: "知识关系", intentional: "意图关系" }
Object.assign(labels, { page_type: "资料类型", body_markdown: "正文", sections: "资料段落", version_number: "版本", status: "状态", surface_meaning: "表层含义", hidden_meaning: "隐藏含义", planned_seed_chapter: "计划埋设章节", planned_reinforce_chapters: "计划强化章节", planned_payoff_scene: "计划回收场景", secret_summary: "秘密概要", reveal_stages: "揭示阶段", stage_index: "阶段顺序", chapter_index: "章节", reveal_content: "揭示内容" })
const formatted = computed(() => typeof props.value === "boolean" ? (props.value ? "是" : "否") : (["level", "page_type", "relation_kind", "entity_type", "importance_level", "reveal_level", "status", "result", "kind", "thread_type", "judgment", "action", "depth", "disposition", "operation"].includes(props.fieldName) ? enums[props.value] || props.value : (props.fieldName === "uncertain_fields" ? labels[props.value] || "待进一步明确" : props.value)))
const visibleFields = computed(() => Object.fromEntries(Object.entries(props.value || {}).filter(([key]) => !hiddenFields.has(key) && !/^(id|novel_id|owner_id|.*_hash|.*_id|.*_ids|.*_ref|.*_refs|confidence|schema_version|layout_version|engine_version|source_keys|item_key|created_by|approved_by|force_create)$/.test(key))))
</script>
