<script setup>
import { ref } from 'vue'
import PreviewIcon from './PreviewIcon.vue'
const props = defineProps({ embedded: Boolean, task: { type: Object, required: true }, candidate: { type: Object, required: true } })
const emit = defineEmits(['update:task','open','navigate'])
const tab = ref('一起创作')
const scope = ref('当前章节')
const selected = ref(['正文表达'])
const batchResult = ref('')
const groups = [
  { title: '推进正文', items: ['续写下一段','让正文更有张力','转换角色视角'] },
  { title: '查证与整理', items: ['检查本章冲突','整理人物与场景','查漏补缺'] },
  { title: '尝试新的写法', items: ['更克制的情绪','更鲜明的动作','按我的要求改写'] },
]
function update(values) { emit('update:task', { ...props.task, ...values }) }
function start(intent) { if (intent === '检查本章冲突') { emit('open', '本章一致性检查', 'conflicts', true); return } update({ status: '进行中', intent, progress: 1 }); tab.value = '任务与结果' }
</script>
<template><div :class="embedded ? 'rd-assistant-embedded' : 'rd-page-scroll'"><div class="rd-assistant-preview" :class="{ 'rd-page-inner': !embedded }">
<header v-if="!embedded" class="rd-page-heading"><div><span class="rd-eyebrow">潮汐来信 / 写作伙伴</span><h1>想法，在对话里向前。</h1><p>一起探索可能，把决定留给你。</p></div><span class="rd-color-icon tone-purple"><PreviewIcon name="sparkles"/></span></header>
<nav class="rd-detail-tabs" aria-label="写作伙伴视图"><button v-for="item in ['一起创作','任务与结果','批次审阅','提醒']" :key="item" :aria-pressed="tab === item" @click="tab = item">{{ item }}</button></nav>
<template v-if="tab === '一起创作'"><div class="rd-assistant-context"><span class="rd-badge tone-blue">第三章 · 潮汐之间</span><label class="rd-field">这次关注<select v-model="scope"><option>当前章节</option><option>选中的段落 · 示例</option><option>当前场景</option><option>已选择的资料</option></select></label><p>本次范围：{{ scope }}。来源改变后需要重新确认。</p></div><section v-for="group in groups" :key="group.title" class="rd-assistant-intents"><h3>{{ group.title }}</h3><button v-for="item in group.items" :key="item" class="rd-suggestion" @click="start(item)">{{ item }}<PreviewIcon name="forward"/></button></section><label class="rd-field">想一起聊聊什么？<textarea :value="task.prompt" rows="3" placeholder="我希望这一幕的情绪更克制一点…" @input="update({ prompt: $event.target.value })"/></label><button class="rd-button purple" :disabled="!task.prompt.trim()" @click="start(task.prompt)">开始讨论示例</button><details><summary class="rd-text-button">之前的讨论</summary><button class="rd-source-link" @click="emit('open', '比较创作建议', 'compare', true)">今天 14:20 · 把沉默留给灯塔 →</button><p>来源：第三章；候选{{ candidate.status === 'adopted' ? '已采用到工作稿 · 演示' : candidate.status === 'rejected' ? '已拒绝 · 演示' : '尚未采用' }}。</p></details></template>
<template v-else-if="tab === '任务与结果'"><span class="rd-badge" :class="task.status === '失败' ? 'tone-orange' : task.status === '进行中' ? 'tone-purple' : 'tone-blue'">{{ task.status }} · 演示</span><h2>{{ task.intent || '关于码头相遇的一些想法' }}</h2><p>关闭面板可以继续写作；只有“停止”会改变本次任务的演示状态。</p><progress v-if="task.status === '进行中'" :value="task.progress" max="3" aria-label="写作伙伴任务进度"/><div v-if="task.status === '失败'" class="rd-inline-notice tone-orange"><strong>! 这次任务没有完成</strong><p>当前输入和已到达的结果仍保留。可重试未完成部分或返回正文。</p></div><div class="rd-local-toolbar"><button v-if="task.status === '进行中'" class="rd-button" @click="update({ status: '已停止' })">停止任务</button><button v-if="['已停止','失败'].includes(task.status)" class="rd-button primary" @click="update({ status: '进行中' })">{{ task.status === '失败' ? '重试未完成部分' : '继续任务示例' }}</button><button class="rd-button purple" @click="emit('open', '比较创作建议', 'compare', true)">重开已有候选 →</button></div><div class="rd-inline-notice tone-purple"><strong>✦ 把沉默留给灯塔</strong><p>来源：第三章 · {{ candidate.review }}。{{ candidate.stale ? '来源已有变化，暂不可采用。' : '建议与工作稿分开保留。' }}</p></div><details><summary class="rd-text-button">手动演示任务反馈</summary><div class="rd-local-toolbar"><button class="rd-button" @click="update({ status: '进行中', progress: 1 })">进行中</button><button class="rd-button" @click="update({ progress: Math.min(3, task.progress + 1) })">下一阶段</button><button class="rd-button" @click="update({ status: '待查看', progress: 3 })">结果到达</button><button class="rd-button" @click="update({ status: '失败' })">可恢复失败</button></div></details></template>
<template v-else-if="tab === '批次审阅'"><h2>一次整理，逐项决定。</h2><p>两项已有结果，一项需要继续查证。每项都有独立的来源与处理状态。</p><ul class="rd-data-list"><li v-for="(item,i) in ['正文表达','白沙港资料','人物关系']" :key="item"><label class="rd-check-label"><input v-model="selected" :value="item" type="checkbox" :disabled="i === 2"/><span>{{ item }}</span></label><div><small>{{ i === 2 ? '未完成 · 来源需要重新确认' : '已产生候选 · 尚未采用' }}</small></div><button class="rd-text-button" @click="emit('open', i === 0 ? '比较创作建议' : '审阅世界资料', 'compare', true)">逐项审阅 →</button></li></ul><div class="rd-local-toolbar"><button class="rd-button" :disabled="!selected.length" @click="batchResult = `已选${selected.length}项，仍需逐项查看来源与独立审查结果`">查看已选范围</button><button class="rd-text-button" @click="update({ status: '进行中', intent: '重新查证人物关系', progress: 2 }); tab = '任务与结果'">仅重试未完成项 →</button></div><p v-if="batchResult" class="rd-inline-notice tone-blue">{{ batchResult }}</p><p class="rd-demonstration">没有把未完成项算作成功，也没有自动采用整批资料。</p></template>
<template v-else><h2>只在重要的时候提醒你。</h2><p>提醒就近说明发生了什么、影响什么、下一步做什么。</p><label class="rd-setting-row"><span>资料出现矛盾时提醒</span><input :checked="task.reminders" type="checkbox" @change="update({ reminders: $event.target.checked })"/></label><label class="rd-setting-row"><span>继续创作前提示待决定事项</span><input :checked="task.beforeWriting" type="checkbox" @change="update({ beforeWriting: $event.target.checked })"/></label><div class="rd-inline-notice tone-orange"><strong>! 灯塔亮起的时间需要核对</strong><p>第三章写落潮前亮起，场景计划记为落潮后。请回看来源，决定故事采用哪个时点。</p><button class="rd-text-button" @click="emit('navigate', 'search')">查看冲突来源 →</button></div><button class="rd-text-button" @click="update({ dismissed: true })">{{ task.dismissed ? '提醒已收起 · 问题仍待决定' : '暂时收起提醒' }}</button></template>
<p class="rd-demonstration">虚构内容与手动反馈，不运行模型。动画与任务成功没有关联。</p>
</div></div></template>
<style>
#redesign-root .rd-assistant-preview{max-width:1020px}#redesign-root .rd-assistant-preview h2{font-size:23px;margin:20px 0 12px}#redesign-root .rd-assistant-preview p{line-height:1.85;color:var(--muted);margin:12px 0}#redesign-root .rd-assistant-preview .rd-assistant-intents{margin-top:20px}#redesign-root .rd-assistant-preview .rd-assistant-intents h3{font-size:12px;color:var(--muted)}#redesign-root .rd-assistant-preview .rd-assistant-context{padding:16px;background:var(--bg);border-radius:12px}#redesign-root .rd-assistant-preview progress{width:100%}#redesign-root .rd-assistant-embedded .rd-assistant-preview .rd-detail-tabs{margin-top:0}#redesign-root .rd-assistant-embedded .rd-assistant-preview .rd-detail-tabs button{font-size:11px;padding:10px 8px}
</style>
