<script setup>
import { ref } from 'vue'
import PreviewIcon from './PreviewIcon.vue'
import PreviewNotice from './PreviewNotice.vue'
import { vReveal } from './motion.js'
import { statusOptions } from './data.js'
const props = defineProps({ page: { type: String, required: true }, theme: { type: String, default: 'light' }, state: { type: String, default: 'normal' }, initialSection: { type: String, default: '全部' }, reducedMotion: Boolean, systemReducedMotion: Boolean })
const emit = defineEmits(['navigate', 'open', 'theme', 'state', 'motion-reduced'])
const section = ref(props.initialSection === '全部' ? '账户' : props.initialSection)
const notifications = ref(true)
const sampleText = ref('潮汐来信')
const motionStage = ref(1)
</script>
<template>
  <div class="rd-page-scroll"><div v-reveal class="rd-page-inner" :class="{ 'rd-reader-inner': page === 'reading' }">
    <PreviewNotice v-if="page !== 'components'" :state="state" @action="emit('open', '状态示例', 'states')"/>
    <template v-if="state !== 'empty' || page === 'components'">
    <template v-if="page === 'components'"><header class="rd-page-heading"><div><h1>组件与状态</h1><p>与样板共用的视觉组件与交互状态</p></div><span class="rd-badge tone-blue">DESIGN LAB</span></header>
      <section class="rd-component-section"><div><span class="rd-eyebrow">01 / COLOR</span><h2>颜色，让重要的事先被看见。</h2></div><div class="rd-palette large"><span v-for="(color,i) in ['blue','purple','green','orange','red']" :key="color" :class="`tone-${color}`"><b>{{ ['↗','✦','✓','!','!'][i] }}</b><strong>{{ ['明确的行动','新的可能','安心的完成','等待你的判断','需要先停一下'][i] }}</strong><small>{{ ['操作与选择','AI 建议，尚未采用','已确认结果','待决定与可恢复失败','阻断风险与危险操作'][i] }}</small></span></div></section>
      <section class="rd-component-section"><div><span class="rd-eyebrow">02 / CONTROLS</span><h2>轻轻一点，明确回应。</h2></div><div class="rd-component-row"><button class="rd-button primary" @click="emit('open', '继续创作', 'scene')"><span class="rd-button-content">继续写作 <PreviewIcon name="forward"/></span></button><button class="rd-button purple" @click="emit('open', '写作伙伴', 'ai', true)"><span class="rd-button-content"><PreviewIcon name="sparkles"/>获取灵感</span></button><button class="rd-button" @click="emit('open', '资料面板', 'detail', true)"><span class="rd-button-content">查看资料</span></button><button class="rd-button subtle" @click="emit('open', '次级操作', 'states')"><span class="rd-button-content">稍后处理</span></button><button class="rd-button danger" @click="emit('open', '移入历史', 'danger')"><span class="rd-button-content">移入历史</span></button><button class="rd-button" disabled><span class="rd-button-content">暂不可用</span></button><button class="rd-button" disabled aria-busy="true"><span class="rd-button-content"><span class="rd-spinner"/>处理中…</span></button></div><div class="rd-component-row"><div class="rd-segments" :style="{ '--rd-segments': 3, '--rd-selected': ['全部','进行中','已完成'].indexOf(section === '账户' ? '全部' : section) }"><button v-for="item in ['全部','进行中','已完成']" :key="item" :aria-pressed="(section === '账户' ? '全部' : section) === item" @click="section = item">{{ item }}</button></div><button class="rd-switch" role="switch" :aria-checked="notifications" aria-label="示例开关" @click="notifications = !notifications"><span/></button><label class="rd-check-label"><input type="checkbox"/>包含归档资料</label><label class="rd-check-label"><input type="radio" name="rd-density" checked/>舒适</label><label class="rd-check-label"><input type="radio" name="rd-density"/>紧凑</label></div></section>
      <section class="rd-component-section"><div><span class="rd-eyebrow">03 / INPUT</span><h2>把想法，轻松表达出来。</h2></div><div class="rd-two-columns"><label class="rd-field">作品名称<input v-model="sampleText"/><small>名称可以随故事成长而改变。</small></label><label class="rd-field">示例校验<input value="" aria-invalid="true" aria-describedby="rd-field-error" placeholder="为故事起个名字"/><small id="rd-field-error" class="rd-danger-text">请填写作品名称。</small></label><label class="rd-field">故事类型<select><option>奇幻</option><option>悬疑</option><option>文学</option></select></label><label class="rd-field">随手记下一个念头<textarea rows="3" placeholder="如果那座灯塔，从未真正熄灭…"/></label></div></section>
      <section class="rd-component-section"><div><span class="rd-eyebrow">04 / FEEDBACK</span><h2>每种状态，都有下一步。</h2></div><div class="rd-filter-pills"><button v-for="option in statusOptions" :key="option.id" :aria-pressed="state === option.id" @click="emit('state', option.id)">{{ option.label }}</button></div><PreviewNotice :state="state" @action="emit('open', '状态的下一步', state === 'conflict' ? 'compare' : 'states')"/><p v-if="state === 'normal'" class="rd-muted">默认状态保持安静。只有发生变化时，才提高提醒的强度。</p><div class="rd-insight tone-purple"><strong>✦ 一个新的创作建议</strong><p>让沈雁的沉默成为下一幕的起点。建议尚未采用，正文没有变化。</p><button class="rd-text-button" @click="emit('open', '比较建议', 'compare')">查看建议 →</button></div><label class="rd-field">整理进度 · 手动演示<progress :value="motionStage" max="3"/>已完成 {{ motionStage }} / 3 个阶段</label><button class="rd-button" @click="motionStage = motionStage === 3 ? 0 : motionStage + 1"><span class="rd-button-content">下一阶段（演示）</span></button></section>
      <section class="rd-component-section"><div class="rd-motion-settings"><div><strong>减少动态效果</strong><p>{{ systemReducedMotion ? '当前系统偏好已启用，预览会始终尊重此设置。' : '切换后重复操作，可比较原速与静态反馈。刷新恢复默认。' }}</p></div><button class="rd-switch" role="switch" aria-label="预览减少动态效果" :aria-checked="reducedMotion" :disabled="systemReducedMotion" @click="emit('motion-reduced', !reducedMotion)"><span/></button></div><div><span class="rd-eyebrow">05 / LAYERS & MOTION</span><h2>展开时有来处，关闭后回到原处。</h2></div><div class="rd-component-row"><button class="rd-button" @click="emit('open', '标准对话框', 'new')"><span class="rd-button-content">打开对话框</span></button><button class="rd-button" @click="emit('open', '资料检查器', 'detail', true)"><span class="rd-button-content">打开侧边抽屉</span></button><button class="rd-button" @click="emit('open', '比较与决定', 'compare')"><span class="rd-button-content">打开比较面板</span></button><button class="rd-button" @click="emit('open', '通知示例', 'notification')"><span class="rd-button-content">查看通知</span></button></div><p class="rd-muted">用原速操作，快速点击两次或在过渡中按 Escape 查看反向与关闭。Tab 检查焦点。可在非模态面板关闭前重新点击原入口；不自动循环播放。</p></section>
    </template>
    </template>
  </div></div>
</template>
