<script setup>
import { computed, reactive, ref, watch } from 'vue'
import PreviewIcon from './PreviewIcon.vue'
import { vReveal } from './motion.js'
const props = defineProps({ theme: { type: String, default: 'light' }, state: { type: String, default: 'normal' }, initialSection: { type: String, default: '账户' } })
const emit = defineEmits(['theme','navigate','open'])
const sections = ['账户','模型连接','图片服务','默认创作偏好','作品偏好','外观','快捷键与帮助']
const section = ref(sections.includes(props.initialSection) ? props.initialSection : '账户')
watch(() => props.initialSection, value => { if (sections.includes(value)) section.value = value })
const displayName = ref('林间')
const connectionStates = reactive({ 模型连接: '未连接', 图片服务: '未连接' })
const connection = computed({ get: () => connectionStates[section.value] || '未连接', set: value => { connectionStates[section.value] = value } })
const connectionName = ref('我的创作连接')
const preferenceScopes = reactive({ '作品偏好': { goal: 1500, viewpoint: '第三人称 · 有限视角', detail: '均衡', reminders: true }, '默认创作偏好': { goal: 1000, viewpoint: '第三人称 · 有限视角', detail: '均衡', reminders: true } })
const prefs = computed(() => preferenceScopes[section.value] || preferenceScopes['作品偏好'])
const dirty = ref(false)
const feedback = ref('')
const resource = ref('尚未导入')
const danger = ref(null)
function saveDemo() { dirty.value = false; feedback.value = '✓ 偏好已保存 · 仅为成功状态演示' }
</script>
<template><div class="rd-page-scroll"><div class="rd-page-inner rd-settings-preview">
<header class="rd-page-heading"><div><h1>账户与偏好</h1><p>让工具，适合你的创作习惯。</p></div><span class="rd-badge tone-blue">林间 · 演示账户</span></header>
<div class="rd-settings-layout"><nav class="rd-settings-nav" aria-label="设置类别"><button v-for="item in sections" :key="item" :aria-current="section === item ? 'page' : undefined" :class="{ selected: section === item }" @click="section = item; feedback = ''">{{ item }}</button></nav>
<section v-reveal="section" class="rd-settings-content" @input="dirty = true; feedback = ''" @change="dirty = true">
<template v-if="section === '账户'"><div class="rd-profile-heading"><span class="rd-avatar profile tone-blue">林</span><div><h2>{{ displayName }}</h2><p>创作者 · 故事探索者</p></div></div><label class="rd-field">显示名称<input v-model="displayName"/></label><div class="rd-settings-group"><div class="rd-detail-line"><span>登录邮箱</span><strong>linjian@example.test</strong></div><div class="rd-detail-line"><span>账户状态</span><strong>演示身份 · 无真实账户</strong></div></div><div class="rd-local-toolbar"><button class="rd-button primary" @click="saveDemo">查看保存反馈</button><button class="rd-button" @click="emit('navigate', 'identity')">作者与故事探索者 →</button></div><details><summary class="rd-text-button">账户管理</summary><p>退出后，正式产品会结束当前登录；删除账户会影响所有作品与私人旅程。</p><div class="rd-local-toolbar"><button class="rd-button" @click="danger = '退出账户'">退出账户</button><button class="rd-button danger" @click="danger = '删除账户'">删除账户</button></div></details></template>
<template v-else-if="section === '模型连接' || section === '图片服务'"><span class="rd-color-icon" :class="section === '模型连接' ? 'tone-purple' : 'tone-teal'"><PreviewIcon :name="section === '模型连接' ? 'sparkles' : 'project'"/></span><h2>{{ section === '模型连接' ? '与你一起创作的模型' : '给世界一个可见的模样' }}</h2><p>{{ section === '模型连接' ? '服务连接属于账户，可用于你的作品与私人旅程。' : '图片服务单独配置；关闭它不影响正文写作。' }}</p><div class="rd-form-grid"><label class="rd-field">连接名称<input v-model="connectionName"/></label><label class="rd-field">服务<select><option>{{ section === '模型连接' ? '示例文本服务' : '示例图片服务' }}</option></select></label><label class="rd-field wide">访问凭据<input type="password" disabled placeholder="预览中不输入真实密钥"/></label></div><div class="rd-inline-notice" :class="connection === '验证失败' ? 'tone-orange' : connection === '验证通过' ? 'tone-green' : 'tone-blue'"><strong>{{ connection === '验证通过' ? '✓ ' : connection === '验证失败' ? '! ' : '' }}{{ connection }} · 演示</strong><p>{{ connection === '验证失败' ? '服务暂时无法响应。已填写的设置保留，请重试或检查连接。' : connection === '验证通过' ? '这是验证通过的状态样式，没有向服务发送请求。' : '只有真实连接验证通过后，正式产品才会将它用于创作。' }}</p><progress v-if="connection === '验证中'" aria-label="验证连接进行中"/></div><div class="rd-local-toolbar"><button class="rd-button primary" :disabled="connection === '验证中'" @click="connection = '验证中'">{{ connection === '验证失败' ? '重试验证示例' : '验证连接示例' }}</button><template v-if="connection === '验证中'"><button class="rd-button" @click="connection = '验证通过'">演示验证通过</button><button class="rd-button" @click="connection = '验证失败'">演示验证失败</button><button class="rd-text-button" @click="connection = '未连接'">取消</button></template></div></template>
<template v-else-if="section === '作品偏好' || section === '默认创作偏好'"><span class="rd-badge tone-blue">{{ section === '作品偏好' ? '仅潮汐来信' : '账户默认 · 用于新作品' }}</span><h2>{{ section === '作品偏好' ? '潮汐来信的创作节奏' : '你的创作习惯' }}</h2><div class="rd-settings-group"><label class="rd-setting-row"><span>每日目标<small>给每天一个温和的起点</small></span><input v-model.number="prefs.goal" type="number" min="0" aria-label="每日目标字数"/></label><label class="rd-setting-row"><span>叙述视角</span><select v-model="prefs.viewpoint"><option>第三人称 · 有限视角</option><option>第一人称</option><option>全知视角</option></select></label><label class="rd-setting-row"><span>建议详略</span><select v-model="prefs.detail"><option>简洁</option><option>均衡</option><option>详细</option></select></label><label class="rd-setting-row"><span>重要创作提醒</span><input v-model="prefs.reminders" type="checkbox"/></label></div><details><summary class="rd-text-button">导入与整理偏好</summary><div class="rd-form-grid"><label class="rd-field">资料整理深度<select><option>均衡整理</option><option>先建立骨架</option><option>深入整理</option></select></label><label class="rd-field">新建议处理<select><option>保留待审阅</option><option>查看持续授权说明</option></select></label></div><p>持续授权范围须在正式任务开始前确认，无法消歧的内容仍待作者决定。</p></details><div class="rd-local-toolbar"><span class="rd-muted">{{ dirty ? '有未保存的示例调整' : '使用当前示例偏好' }}</span><button class="rd-button primary" @click="saveDemo">演示保存偏好</button></div></template>
<template v-else-if="section === '外观'"><h2>晴日与静夜</h2><p>平静的正文，清楚的行动。</p><div class="rd-theme-cards"><button v-for="mode in ['light','dark']" :key="mode" :aria-pressed="theme === mode" @click="emit('theme', mode)"><span class="rd-theme-mini" :class="mode"><i/><b/><span/></span><strong>{{ mode === 'light' ? '晴日' : '静夜' }}</strong><span>{{ theme === mode ? '✓ 已选择' : '选择外观' }}</span></button></div><h3>主题资源</h3><p>把一组创作表面、字体和内容配色放在一起。</p><div class="rd-model-card"><span class="rd-mini-cover">潮</span><div><strong>白沙海岸</strong><small>{{ resource }} · 示例主题</small></div></div><div class="rd-local-toolbar"><button class="rd-button" @click="resource = '已预览，等待采用'">演示导入主题</button><button class="rd-button" @click="resource = '导出成功反馈'">演示导出主题</button><button class="rd-text-button" @click="resource = '文件无法识别'">查看导入失败</button></div><div v-if="resource === '已预览，等待采用'" class="rd-inline-notice tone-purple"><strong>✦ 预览中的主题</strong><p>采用后才会替换当前外观；正式产品仅保存在此浏览器。</p><button class="rd-button" @click="resource = '已采用'">演示采用</button></div><p v-else-if="resource === '文件无法识别'" class="rd-inline-notice tone-orange">! 无法识别主题文件，当前外观保持不变。请换用有效的主题资源包。</p><div class="rd-palette"><span v-for="(color,i) in ['blue','purple','green','orange','red']" :key="color" :class="`tone-${color}`">{{ ['操作','灵感','完成','待决定','风险'][i] }}</span></div></template>
<template v-else><h2>让操作跟得上灵感</h2><ul class="rd-data-list"><li><div><strong>查找作品资料</strong><small>保留当前写作位置</small></div><kbd>⌘ K</kbd></li><li><div><strong>关闭当前面板 / 退出专注</strong><small>回到触发操作的位置</small></div><kbd>Esc</kbd></li><li><div><strong>逐项访问控件</strong><small>使用方向键操作菜单</small></div><kbd>Tab</kbd></li></ul><div class="rd-local-toolbar"><button class="rd-button" @click="emit('navigate', 'search')">打开查找</button><button class="rd-button" @click="emit('navigate', 'components')">组件与动效</button></div></template>
<div v-if="danger" class="rd-inline-notice tone-red" role="alert"><strong>{{ danger }}？</strong><p>{{ danger === '删除账户' ? '正式操作将影响账户下所有作品和私人旅程，不能撤销。' : '正式操作将结束当前登录，未保存内容应先保全。' }}这里仅展示确认样式。</p><div class="rd-local-toolbar"><button class="rd-button" @click="danger = null">保留并返回</button><button class="rd-button danger" @click="feedback = '确认结果演示，真实账户未改变'; danger = null">查看确认后反馈</button></div></div>
<p v-if="feedback" role="status" class="rd-inline-notice tone-green">{{ feedback }}</p><p class="rd-demonstration">设置调整只存在于本次设计预览，不读取账户、不保存偏好、不发送验证请求。</p>
</section></div></div></div></template>
<style>
#redesign-root .rd-settings-preview{max-width:1140px}#redesign-root .rd-settings-preview .rd-settings-nav button[aria-current='page']{background:var(--blue-bg);color:var(--blue)}#redesign-root .rd-settings-preview .rd-settings-content>h2{margin:18px 0 10px}#redesign-root .rd-settings-preview .rd-settings-content>p{line-height:1.9;margin:12px 0;color:var(--muted)}#redesign-root .rd-settings-preview .rd-setting-row small{display:block;font-weight:400;color:var(--muted)}#redesign-root .rd-settings-preview .rd-model-card small{display:block;color:var(--muted)}
</style>
