<script setup>
import { computed, ref, watch } from 'vue'
import PreviewIcon from './PreviewIcon.vue'
import { vReveal } from './motion.js'
const props = defineProps({ state: { type: String, default: 'normal' }, initialSection: { type: String, default: '全部' } })
const emit = defineEmits(['open', 'navigate'])
const tabs = ['故事总览','篇章','剧情线','场景']
const tab = ref(props.initialSection.startsWith('场景/') ? '场景' : tabs.includes(props.initialSection) ? props.initialSection : '故事总览')
watch(() => props.initialSection, value => { if (value.startsWith('场景/')) { tab.value = '场景'; selection.value = value.slice(3) } else if (tabs.includes(value)) tab.value = value })
const selection = ref(props.initialSection.startsWith('场景/') ? props.initialSection.slice(3) : null)
const sceneTab = ref('本场')
const query = ref('')
const sceneStatus = ref('全部状态')
const sceneSource = ref('全部来源')
const note = ref('林舟寻找答案，沈雁试图保守秘密。一张海图把他们带到同一个地点。')
const goal = ref('让灯塔的亮起，迫使两人共同作出选择。')
const editing = ref(false)
const proposalState = ref('草案')
const simulation = ref('尚未排演')
const sceneNames = ref(['林舟回到白沙港','码头上的初次相遇','夜探灯塔','海图的新航线'])
const createName = ref('')
const creating = ref(false)
const feedback = ref('')
const retried = ref(false)
watch(() => props.state, () => { retried.value = false; feedback.value = '' })
const scenes = computed(() => sceneNames.value.filter((name, i) => name.includes(query.value) && (sceneStatus.value === '全部状态' || (i === 1 ? '正在写' : i === 0 ? '已完成' : '待展开') === sceneStatus.value) && (sceneSource.value === '全部来源' || (i < 2 ? '作者创建' : '整理建议') === sceneSource.value)))
function select(item) { selection.value = item; sceneTab.value = '本场'; editing.value = false; feedback.value = '' }
function createScene() { if (!createName.value.trim()) return; sceneNames.value.push(createName.value.trim()); select(createName.value.trim()); createName.value = ''; creating.value = false }
</script>
<template>
  <div class="rd-page-scroll"><div class="rd-page-inner">
    <header class="rd-page-heading"><div><span class="rd-eyebrow">潮汐来信 / 故事结构</span><h1>让每一步，都通向故事。</h1><p>从故事全貌，到一个眼神里的转折。</p></div><button class="rd-button purple" @click="emit('open', '梳理故事结构', 'ai', true)"><span class="rd-button-content"><PreviewIcon name="sparkles"/>梳理思路</span></button></header>
    <nav class="rd-segments rd-fit" :style="{ '--rd-segments': 4, '--rd-selected': tabs.indexOf(tab) }" aria-label="故事结构视图"><button v-for="item in tabs" :key="item" :aria-pressed="tab === item" @click="tab = item; selection = null">{{ item }}</button></nav>
    <div v-if="state === 'loading'" class="rd-dense-empty" role="status"><span class="rd-spinner"/> 正在展开故事结构…</div>
    <div v-else-if="state === 'empty'" class="rd-dense-empty"><h2>故事还没有画下第一笔</h2><p>先写一句故事的起点，或建立第一个篇章。</p><button class="rd-button primary" @click="emit('open', '写下故事起点', 'new')">建立结构示例</button></div>
    <template v-else>
      <div v-if="state === 'error' && !retried" class="rd-inline-notice tone-orange"><strong>! 最新结构暂时无法打开</strong><p>下面保留上次示例，可以继续阅读；稍后重新读取最新结构。</p><button class="rd-button" @click="retried = true; feedback = '✓ 重新读取完成 · 演示'">重试读取示例</button></div>
      <section v-if="tab === '故事总览'" class="rd-story-premise"><span class="rd-eyebrow">故事的心脏</span><h2>当一个人终于找到离开的理由，<br>她还会选择回来吗？</h2><p>{{ note }}</p><div class="rd-local-toolbar"><button class="rd-text-button" @click="editing = !editing">{{ editing ? '收起编辑' : '编辑故事梗概' }} →</button><button class="rd-text-button" @click="emit('open', '比较结构方案', 'compare', true)">查看结构建议 →</button></div><label v-if="editing" class="rd-field">故事梗概<textarea v-model="note" rows="4"/><small>仅保留在本次预览</small></label></section>
      <div v-if="tab === '故事总览' || tab === '篇章'" class="rd-act-grid"><button v-for="(act,i) in ['潮声','暗流','归岸']" :key="act" class="rd-act" :aria-pressed="selection === act" @click="select(act)"><span class="rd-act-index" :class="['tone-blue','tone-purple','tone-teal'][i]">0{{ i + 1 }}</span><h2>{{ act }}</h2><p>{{ ['回到故乡。海图上的秘密，让两个陌生人走到一起。','真相浮出水面，每个人都必须重新选择相信什么。','潮水退去之后，留下来的会是新的开始。'][i] }}</p><div class="rd-act-footer"><span>{{ [6,8,4][i] }} 章 · {{ i === 0 ? '2章已完成' : '故事构思中' }}</span><PreviewIcon name="forward"/></div></button></div>
      <div v-if="tab === '剧情线'" class="rd-thread-list"><button v-for="(name,i) in ['寻找父亲的航线','沈雁与灯塔的秘密','港口即将到来的大潮']" :key="name" class="rd-thread" :class="['tone-blue','tone-purple','tone-orange'][i]" :aria-pressed="selection === name" @click="select(name)"><span class="rd-eyebrow">线索 {{ i+1 }}</span><h3>{{ name }}</h3><div class="rd-thread-track"><span/><span/><span/><span/><span/></div><p>{{ ['发现 → 追寻 → 怀疑 → 抉择 → 归来','沉默 → 试探 → 袒露 → 共同承担','预兆 → 靠近 → 风暴 → 平静'][i] }}</p></button></div>
      <template v-if="tab === '场景'"><div class="rd-local-toolbar"><label class="rd-field">查找场景<input v-model="query" placeholder="标题、冲突或场景目标"/></label><label class="rd-field">进展<select v-model="sceneStatus"><option>全部状态</option><option>待展开</option><option>正在写</option><option>已完成</option></select></label><label class="rd-field">来源<select v-model="sceneSource"><option>全部来源</option><option>作者创建</option><option>整理建议</option></select></label><button class="rd-button primary" @click="creating = !creating">新建场景</button></div><details><summary class="rd-text-button">更多筛选与注意原因</summary><div class="rd-form-grid"><label class="rd-field">章节范围<select><option>全书</option><option>第一部</option><option>当前第三章</option></select></label><label class="rd-field">注意原因<select><option>全部</option><option>资料不完整</option><option>来源已变化</option><option>需要作者检查</option></select></label><label class="rd-field">整理阶段<select><option>全部阶段</option><option>初步拆分</option><option>已核对</option></select></label></div><p class="rd-demonstration">高级筛选样式演示；当前小样本按搜索、进展与来源筛选。</p></details><form v-if="creating" class="rd-local-toolbar" @submit.prevent="createScene"><label class="rd-field">新场景名称<input v-model="createName" required placeholder="这一幕的名字"/></label><button class="rd-button primary">创建示例场景</button><button type="button" class="rd-button" @click="creating = false">取消</button></form><ul class="rd-data-list"><li v-for="name in scenes" :key="name"><span class="rd-small-icon tone-blue"><PreviewIcon name="outline"/></span><div><strong>{{ name }}</strong><small>第一部 · {{ name.includes('初次') ? '第三章 · 林舟视角' : '场景草案' }}</small></div><button class="rd-button" @click="select(name)">打开工作台 →</button></li></ul><div v-if="!scenes.length" class="rd-dense-empty">没有符合条件的场景。调整筛选或新建一个。</div></template>
      <section v-if="selection" v-reveal="selection" class="rd-detail-surface rd-structure-detail"><div class="rd-detail-heading"><div><span class="rd-eyebrow">{{ tab === '场景' ? '故事结构 / 场景工作台' : '故事结构 / 详情' }}</span><h2>{{ selection }}</h2></div><button class="rd-icon-button" aria-label="关闭结构详情" @click="selection = null"><PreviewIcon name="close"/></button></div>
        <template v-if="tab === '场景'"><nav class="rd-detail-tabs"><button v-for="item in ['本场','人物与资料','场景剧本','排演结果']" :key="item" :aria-pressed="sceneTab === item" @click="sceneTab = item">{{ item }}</button></nav><div v-if="sceneTab === '本场'" class="rd-form-grid"><label class="rd-field">场景目标<textarea v-model="goal" rows="3"/></label><label class="rd-field">当前视角<select><option>林舟</option><option>沈雁</option></select></label><label class="rd-field">关联章节<select><option>第三章 · 潮汐之间</option><option>第四章 · 没有名字的航线</option></select></label><div><span class="rd-badge tone-blue">当前场景 · 示例</span><p>开始：错过渡船<br>转折：沈雁认出海图<br>结果：两人决定夜探灯塔</p></div></div>
        <div v-else-if="sceneTab === '人物与资料'"><div class="rd-inline-notice tone-orange"><strong>! 林舟还不知道父亲与沈雁的关系</strong><p>人物知识截至码头初遇。后续场景中的真相不能提前进入她的对白。</p></div><ul class="rd-data-list"><li v-for="item in ['林舟 · 追寻父亲','沈雁 · 保守秘密','白沙港 · 落潮时点']" :key="item"><div><strong>{{ item }}</strong><small>来源：本章资料 · 示例</small></div><button class="rd-text-button" @click="emit('navigate', 'search')">回看来源 →</button></li></ul></div>
        <div v-else-if="sceneTab === '场景剧本'"><label class="rd-field">剧本状态演示<select v-model="proposalState"><option>草案</option><option>已采用</option><option>来源已过期</option></select></label><div class="rd-inline-notice" :class="proposalState === '已采用' ? 'tone-green' : proposalState === '来源已过期' ? 'tone-orange' : 'tone-purple'"><strong>{{ proposalState === '来源已过期' ? '! 来源已变化，请先核对' : proposalState === '已采用' ? '✓ 已采用的场景剧本 · 演示' : '✦ 场景剧本草案 · 尚未采用' }}</strong><p>林舟摊开海图；沈雁按住银色记号；灯塔闪烁迫使两人中断谈话。</p></div><button class="rd-button purple" :disabled="proposalState === '来源已过期'" @click="emit('open', '审阅场景剧本', 'compare', true)">比较并决定</button><button v-if="proposalState === '来源已过期'" class="rd-button" @click="proposalState = '草案'">演示重新核对来源</button></div>
        <div v-else><div class="rd-detail-heading"><h3>在落笔前，试演一次。</h3><span class="rd-badge tone-purple">{{ simulation }}</span></div><p>根据场景目标推演人物反应。排演不改变正文，也不成为故事已经发生的事实。</p><label class="rd-field">排演关注点<textarea rows="2" placeholder="试着让沈雁在这一幕里更犹豫…"/></label><div class="rd-local-toolbar"><button class="rd-button purple" @click="simulation = '排演中'">演示排演开始</button><button v-if="simulation === '排演中'" class="rd-button" @click="simulation = '已停止'">停止</button><button v-if="simulation === '排演中'" class="rd-button" @click="simulation = '有结果待查看'">演示结果到达</button><button v-if="simulation === '已停止'" class="rd-button" @click="simulation = '排演中'">继续排演示例</button></div><progress v-if="simulation === '排演中'" aria-label="排演进行中"/><div v-if="simulation === '有结果待查看'" class="rd-inline-notice tone-purple"><strong>一个可能的反应</strong><p>沈雁先收起风灯，才去看海图。对林舟来说，这个动作比解释更像一句拒绝。</p><button class="rd-text-button" @click="emit('open', '排演结果与原稿', 'compare', true)">对照原稿 →</button></div></div><div class="rd-local-toolbar"><button class="rd-button" @click="emit('navigate', 'writing')">回到本章写作</button><button class="rd-text-button" @click="feedback = '✓ 已加入本次创作计划 · 演示'">加入创作计划</button></div></template>
        <template v-else><p>{{ note }}</p><div class="rd-table-scroll"><table class="rd-data-table"><thead><tr><th>线索</th><th>埋下</th><th>揭示</th><th>当前表达</th></tr></thead><tbody><tr><td>海图背面的银色记号</td><td>第三章</td><td>第九章</td><td><span class="rd-badge tone-purple">尚未揭晓</span></td></tr><tr><td>失去灯火的三年</td><td>第一章</td><td>第六章</td><td><span class="rd-badge tone-blue">持续推进</span></td></tr></tbody></table></div><div class="rd-local-toolbar"><button class="rd-button" @click="editing = !editing">编辑摘要</button><button class="rd-button purple" @click="emit('open', '结构方案比较', 'compare', true)">比较结构建议</button><button class="rd-text-button" @click="tab = '场景'; selection = null">查看关联场景 →</button></div><label v-if="editing" class="rd-field">结构摘要<textarea v-model="note" rows="4"/></label></template>
      </section><p v-if="feedback" role="status" class="rd-inline-notice tone-green">{{ feedback }}</p><p class="rd-demonstration">虚构结构与本地交互示例。刷新恢复初始内容，不调用模型或保存作品。</p>
    </template>
  </div></div>
</template>
<style>
#redesign-root .rd-structure-detail{margin-top:26px}#redesign-root .rd-structure-detail>.rd-form-grid p{line-height:2}#redesign-root .rd-structure-detail progress{width:100%}#redesign-root .rd-story-premise .rd-field{max-width:640px}#redesign-root .rd-act[aria-pressed='true']{box-shadow:0 0 0 2px var(--blue)}
</style>
