"""Phase 2 scene entity extraction configuration constants."""

from __future__ import annotations

MAX_PHASE2_SCENE_RETRIES = 3
MAX_PHASE2_CONSECUTIVE_TRANSPORT_FAILURES = 3
PHASE2_SCENE_TIMEOUT_GRACE_SECONDS = 15
PHASE2_BULK_MAX_SCENES = 12
PHASE2_BULK_GROUP_SIZE = 1
PHASE2_BULK_LLM_TIMEOUT_SECONDS = 60
PHASE2_BULK_PROVIDER_TIMEOUT_SECONDS = 45
PHASE2_BULK_MAX_TOKENS = 4096
PHASE2_BATCH_SIZE_SCENES = 12
PHASE2_BATCH_CONCURRENCY = 6
PHASE2_BOUNDARY_SCENES = 2
PHASE2_PARALLEL_SCENE_CONCURRENCY = 4
PHASE2_PARALLEL_PROVIDER_TIMEOUT_SECONDS = 120
PHASE2_PARALLEL_LLM_TIMEOUT_SECONDS = 135
PHASE2_SMALL_SAMPLE_MIN_SCENES = 8
PHASE2_SMALL_SAMPLE_MIN_ENTITIES = 18
PHASE2_SMALL_SAMPLE_TARGET_ENTITIES = 29
PHASE2_SMALL_SAMPLE_SUPPLEMENT_TIMEOUT_SECONDS = 90
PHASE2_SMALL_SAMPLE_SUPPLEMENT_CHAPTER_CHAR_LIMIT = 4200
PHASE2_SMALL_SAMPLE_SUPPLEMENT_TOTAL_CHAR_LIMIT = 36000
