from pathlib import Path
import json, html, re
ROOT=Path(__file__).resolve().parent
D=json.loads((ROOT/'design.json').read_text())
S=D['screens']; entries=[{k:s[k] for k in ('sid','title','category','w','h','subtitle','notes')} | {'svg':(ROOT/'screens'/f'{s["sid"]}.svg').read_text()} for s in S]
css='''*{box-sizing:border-box}body{margin:0;background:#ecebe7;color:#1e2a3b;font-family:"Noto Sans SC","Microsoft YaHei",sans-serif}button,input,select{font:inherit}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #6d5c95;outline-offset:3px}header{height:66px;background:#fffdf9;border-bottom:1px solid #dedcd5;display:flex;align-items:center;gap:18px;padding:0 22px}header strong{font-size:18px}header .sub{font-size:12px;color:#667281;flex:1}.tools{display:flex;gap:8px}.tools button{background:#f6f4f0;color:#284c56;border:1px solid #dedcd5;border-radius:8px;padding:8px 12px;font-size:12px}.layout{display:flex;height:calc(100vh - 66px)}nav{width:252px;flex-shrink:0;background:#fffdf9;padding:18px 14px;overflow:auto;border-right:1px solid #dedcd5}#filter{width:100%;border:1px solid #dedcd5;background:#f6f4f0;padding:11px;border-radius:9px;color:#1e2a3b}.navgroup{font-size:11px;color:#667281;margin:22px 8px 8px}.navitem{display:block;width:100%;text-align:left;background:none;border:0;border-radius:8px;padding:10px;font-size:12px;line-height:1.6;color:#485365}.navitem.active{background:#e5eeeb;color:#284c56;font-weight:600}.navitem small{opacity:.7;margin-right:8px}main{flex:1;min-width:0;position:relative;display:flex;flex-direction:column}.meta{display:flex;gap:12px;padding:15px 24px;align-items:center;font-size:12px;color:#667281}#screenTitle{font-size:15px;color:#1e2a3b;flex:1}#stage{flex:1;min-height:0;overflow:auto;padding:12px 24px 28px;display:flex;align-items:flex-start;justify-content:center}#art{box-shadow:0 8px 40px #142c3620;line-height:0;flex-shrink:0;background:#f6f4f0}#art svg{display:block;width:100%;height:100%}#art [data-target]{cursor:pointer}#art [data-target]:hover{filter:brightness(.97)}#art [data-target]:focus{outline:none;filter:drop-shadow(0px 0px 2px #6d5c95)}.hotspots #art [data-target]{filter:drop-shadow(0 0 3px #9c64bd);outline:2px solid #6d5c9560}#notes{position:absolute;right:20px;top:58px;z-index:5;width:340px;background:#fffdf9;padding:25px;box-shadow:0 12px 44px #17262c35;border:1px solid #dedcd5;border-radius:14px;line-height:1.8;font-size:13px}#notes[hidden]{display:none}#notes button{float:right;border:0;background:#eeebe5;border-radius:6px;padding:4px 9px}#toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#1e2a3b;color:#fff;padding:12px 24px;border-radius:10px;z-index:10;font-size:13px}#toast[hidden]{display:none}.flag{color:#6d5c95;font-size:11px}@media(max-width:850px){nav{width:190px}.tools button{padding:7px}.sub{display:none}header{gap:10px;padding:0 12px}#stage{padding:8px}.meta{padding:12px}header strong{font-size:14px}}@media(max-width:580px){nav{display:none}header{height:106px;flex-wrap:wrap;align-content:center;gap:7px}.tools{width:100%}.layout{height:calc(100vh - 106px)}#notes{width:calc(100% - 40px)}.meta .flag{display:none}}'''
js=r'''const SCREENS=__SCREENS__;const byId=Object.fromEntries(SCREENS.map(s=>[s.sid,s]));let active='S01',trail=[],natural=false;const art=document.querySelector('#art'),stage=document.querySelector('#stage');
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.hidden=true,2600)}
function nav(){let q=document.querySelector('#filter').value.trim().toLowerCase();let group='';document.querySelector('#list').replaceChildren();for(const s of SCREENS){if(q&&!(`${s.sid} ${s.title} ${s.category}`.toLowerCase().includes(q)))continue;if(s.category!==group){const h=document.createElement('div');h.className='navgroup';h.textContent=group=s.category;document.querySelector('#list').append(h)}const b=document.createElement('button');b.className='navitem'+(s.sid===active?' active':'');b.dataset.id=s.sid;b.textContent=s.sid+'  '+s.title;b.onclick=()=>go(s.sid);document.querySelector('#list').append(b)}}
function fit(){const s=byId[active];let scale=natural?1:Math.min((stage.clientWidth-48)/s.w,(stage.clientHeight-36)/s.h,1);scale=Math.max(.12,scale);art.style.width=s.w*scale+'px';art.style.height=s.h*scale+'px';document.querySelector('#scale').textContent=Math.round(scale*100)+'%';document.querySelector('#zoom').textContent=natural?'适应窗口':'100%'}
function go(id,push=true){if(!byId[id])return;if(id===active){toast('仅展示操作状态；原型不会保存、计费或删除数据。');return}if(push)trail.push(active);active=id;render();history.replaceState(null,'','#'+id)}
function render(){const s=byId[active];art.innerHTML=s.svg;document.querySelector('#screenTitle').textContent=s.sid+' · '+s.title;document.querySelector('#position').textContent=(SCREENS.indexOf(s)+1)+' / '+SCREENS.length;const p=document.querySelector('#noteBody');p.replaceChildren();for(const text of [s.subtitle,...s.notes,'所有文字、数值和图像为虚构样例。按钮用于演示目标工作流，不执行真实业务。']){if(!text)continue;let d=document.createElement('p');d.textContent=text;p.append(d)}nav();fit();stage.scrollTo(0,0);document.title='NovelCraft V4 · '+s.title}
art.addEventListener('click',e=>{const n=e.target.closest('[data-target]');if(n)go(n.dataset.target)});art.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const n=e.target.closest('[data-target]');if(n){e.preventDefault();go(n.dataset.target)}}});document.querySelector('#filter').addEventListener('input',nav);document.querySelector('#prev').onclick=()=>{let i=SCREENS.findIndex(s=>s.sid===active);go(SCREENS[(i-1+SCREENS.length)%SCREENS.length].sid)};document.querySelector('#next').onclick=()=>{let i=SCREENS.findIndex(s=>s.sid===active);go(SCREENS[(i+1)%SCREENS.length].sid)};document.querySelector('#back').onclick=()=>{if(trail.length)go(trail.pop(),false);else toast('这是当前浏览起点。')};document.querySelector('#zoom').onclick=()=>{natural=!natural;fit()};document.querySelector('#hot').onclick=()=>document.body.classList.toggle('hotspots');document.querySelector('#info').onclick=()=>{document.querySelector('#notes').hidden=!document.querySelector('#notes').hidden};document.querySelector('#close').onclick=()=>document.querySelector('#notes').hidden=true;document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('#notes').hidden=true}else if(e.key==='ArrowRight'&&e.target.tagName!=='INPUT')document.querySelector('#next').click();else if(e.key==='ArrowLeft'&&e.target.tagName!=='INPUT')document.querySelector('#prev').click()});window.addEventListener('resize',fit);window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(byId[id]&&id!==active)go(id)});active=byId[location.hash.slice(1)]?location.hash.slice(1):'S01';render();'''.replace('__SCREENS__',json.dumps(entries,ensure_ascii=False).replace('</',r'<\/'))
html_doc='''<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NovelCraft V4 高保真原型</title><style>'''+css+'''</style></head><body><header><strong>NovelCraft · V4 HiFi</strong><span class="sub">离线设计原型 · 48 个工作流/状态 + 1 个设计规范 · 不执行真实业务</span><div class="tools"><button id="back">返回</button><button id="prev">上一稿</button><button id="next">下一稿</button><button id="zoom">100%</button><button id="hot">热点</button><button id="info">设计说明</button></div></header><div class="layout"><nav aria-label="设计画面"><input id="filter" aria-label="查找画面" placeholder="查找画面或工作流"><div id="list"></div></nav><main><div class="meta"><strong id="screenTitle"></strong><span class="flag">示例数据 · 非生产界面</span><span id="position"></span><span id="scale"></span></div><div id="stage"><div id="art"></div></div><aside id="notes" hidden><button id="close" aria-label="关闭设计说明">×</button><h3>这张画面的设计意图</h3><div id="noteBody"></div></aside></main></div><div role="status" id="toast" hidden></div><script>'''+js+'''</script></body></html>'''
(ROOT/'prototype.html').write_text(html_doc)
# Native Figma importer. No network; dataset is embedded and never contains user manuscripts.
plugin=r'''/* NovelCraft V4 — offline native-layer design importer.
 * Runtime: Figma Plugin API 1.0.0, Design editor. No network access.
 * Fixed artboards + native editable text/vector layers; Auto Layout control components.
 * Do not overwrite existing content. Each run creates one new named page.
 * Figma execution was NOT possible in the authoring session (MCP quota exhausted).
 */
const DESIGN=__DESIGN__;
figma.showUI(__html__, {width:430,height:430,themeColors:true});
let running=false,cancelled=false,createdIds=[],warnings=[],links=[],roots={},components={},variables={},fontCache={};
function status(text,progress){figma.ui.postMessage({type:'status',text,progress});}
function rgb(hex){hex=DESIGN.palette[hex]||hex; if(!hex||!/^#[0-9a-f]{6}$/i.test(hex))return {r:0,g:0,b:0};return {r:parseInt(hex.slice(1,3),16)/255,g:parseInt(hex.slice(3,5),16)/255,b:parseInt(hex.slice(5,7),16)/255};}
function paint(key){if(!key)return [];let p={type:'SOLID',color:rgb(key)};if(variables[key])p=figma.variables.setBoundVariableForPaint(p,'color',variables[key]);return [p];}
function track(n){createdIds.push(n.id);return n;}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');}
async function font(family,weight){let k=family+'/'+weight;if(fontCache[k])return fontCache[k];const options=[{family,style:weight},{family,style:'Regular'},{family:'Noto Sans SC',style:'Regular'},{family:'Inter',style:'Regular'}];for(const f of options){try{await figma.loadFontAsync(f);fontCache[k]=f;if(f.family!==family||f.style!==weight)warnings.push('字体替代：'+k+' → '+f.family+'/'+f.style);return f;}catch(e){}}throw new Error('没有可加载字体，已停止；已完成画板保留。');}
async function tokens(){const suffix=new Date().toISOString().slice(0,16).replace(/[:T]/g,'-');const raw=figma.variables.createVariableCollection('NC V4 原语 '+suffix),sem=figma.variables.createVariableCollection('NC V4 语义 '+suffix),layout=figma.variables.createVariableCollection('NC V4 布局 '+suffix);for(const k of Object.keys(DESIGN.palette)){let p=figma.variables.createVariable('raw/'+k,raw,'COLOR');p.scopes=[];p.setValueForMode(raw.defaultModeId,rgb(k));p.setVariableCodeSyntax('WEB','var(--nc-v4-raw-'+k+')');let v=figma.variables.createVariable(k,sem,'COLOR');v.scopes=k==='border'?['STROKE_COLOR']:['FRAME_FILL','SHAPE_FILL','TEXT_FILL'];v.setValueForMode(sem.defaultModeId,figma.variables.createVariableAlias(p));v.setVariableCodeSyntax('WEB','var(--nc-'+k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+')');variables[k]=v;}for(const n of [4,8,12,16,24,32,48]){let v=figma.variables.createVariable('space/'+n,layout,'FLOAT');v.scopes=['GAP'];v.setValueForMode(layout.defaultModeId,n);v.setVariableCodeSyntax('WEB','var(--nc-space-'+n+')');}}
async function textNode(n,parent){const t=track(figma.createText());t.fontName=await font(n.font,n.weight);t.fontSize=n.size;t.lineHeight={unit:'PIXELS',value:n.lh};t.characters=n.text;t.fills=paint(n.color);t.textAutoResize='NONE';t.resize(Math.max(n.w,1),Math.max(n.h,1));t.textAlignHorizontal=n.align==='center'?'CENTER':'LEFT';parent.appendChild(t);t.x=n.x;t.y=n.y;t.name=n.name;return t;}
async function componentBase(n,page){const key=n.component; if(components[key])return components[key];let c=track(figma.createComponent());c.name='NC/'+key;c.layoutMode='HORIZONTAL';c.primaryAxisSizingMode='FIXED';c.counterAxisSizingMode='FIXED';c.primaryAxisAlignItems='CENTER';c.counterAxisAlignItems='CENTER';c.resize(220,n.h);c.paddingLeft=12;c.paddingRight=12;c.paddingTop=4;c.paddingBottom=4;c.itemSpacing=8;c.cornerRadius=n.r||0;c.fills=paint(n.fill);c.strokes=paint(n.stroke);c.clipsContent=false;c.description='NovelCraft V4 离线设计控件；单卡一个主操作，状态含明确文字。';page.appendChild(c);c.x=100+Object.keys(components).length*240;c.y=70;let source=n.children.find(x=>x.type==='text');let t=await textNode({...source,x:0,y:0,w:196},c);t.textAutoResize='WIDTH_AND_HEIGHT';let prop=c.addComponentProperty('Label','TEXT',n.label);t.componentPropertyReferences={characters:prop};components[key]={node:c,prop};return components[key];}
async function build(n,parent,page){if(cancelled)throw new Error('已暂停导入。完成画板保留，可在新页面重新导入所需范围。');let out;
 if(n.component){let base=await componentBase(n,page);out=track(base.node.createInstance());parent.appendChild(out);out.resize(n.w,n.h);out.setProperties({[base.prop]:n.label});out.x=n.x;out.y=n.y;out.name=n.name;
 }else if(n.type==='text'){out=await textNode(n,parent);
 }else if(n.type==='frame'){out=track(figma.createFrame());out.name=n.name;out.resize(Math.max(n.w,1),Math.max(n.h,1));out.fills=paint(n.fill);out.strokes=paint(n.stroke);out.strokeWeight=1;out.cornerRadius=n.r||0;out.clipsContent=!!n.clip;parent.appendChild(out);out.x=n.x;out.y=n.y;for(const child of n.children||[])await build(child,out,page);
 }else if(n.type==='rect'||n.type==='ellipse'){out=track(n.type==='rect'?figma.createRectangle():figma.createEllipse());out.resize(Math.max(n.w,1),Math.max(n.h,1));out.fills=paint(n.fill);out.strokes=paint(n.stroke);out.strokeWeight=n.sw||1;if(n.type==='rect')out.cornerRadius=n.r||0;parent.appendChild(out);out.x=n.x;out.y=n.y;out.name=n.name;
 }else if(n.type==='path'){const width=Math.max(24,parent.width||1440),height=Math.max(24,parent.height||960);const attrs=`fill="${esc(DESIGN.palette[n.fill]||n.fill||'none')}" stroke="${esc(DESIGN.palette[n.stroke]||n.stroke||'none')}" stroke-width="${n.sw||1}" stroke-linecap="round" stroke-linejoin="round"`;const dash=n.dash?` stroke-dasharray="${esc(n.dash)}"`:'';const transform=n.scale?` transform="scale(${n.scale})"`:'';out=track(figma.createNodeFromSvg(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><path d="${esc(n.d)}" ${attrs}${dash}${transform}/></svg>`));parent.appendChild(out);out.x=0;out.y=0;out.name=n.name+' / editable vector';out.clipsContent=false;
 }else throw new Error('未知设计节点：'+n.type);
 if(n.opacity!==undefined)out.opacity=n.opacity;if(n.target)links.push({node:out,target:n.target});return out;
}
figma.ui.onmessage=async msg=>{if(msg.type==='cancel'){cancelled=true;return;}if(msg.type==='close'){figma.closePlugin();return;}if(msg.type!=='create'||running)return;running=true;cancelled=false;warnings=[];createdIds=[];links=[];roots={};components={};variables={};try{if(figma.editorType!=='figma')throw new Error('请在 Figma Design 文件中运行。');const selected=DESIGN.screens.filter(s=>msg.scope==='all'||(msg.scope==='map'&&['S20','S21','S22','S23','S24','S25','S26','S36','S39','S46'].includes(s.sid))||(msg.scope==='mobile'&&s.mobile)||(msg.scope==='core'&&['DS00','S01','S02','S04','S05','S06','S09','S10','S13','S16','S20','S28','S33','S37'].includes(s.sid)));const page=track(figma.createPage());page.name='NC V4 HiFi · '+new Date().toISOString().slice(0,16);await figma.setCurrentPageAsync(page);await tokens();let i=0;for(const s of selected){status('正在创建 '+s.sid+' · '+s.title,Math.round(i/selected.length*100));const n=await build(s,page,page);n.x=100+(i%4)*1560;n.y=360+Math.floor(i/4)*1120;roots[s.sid]=n;i++;await new Promise(resolve=>setTimeout(resolve,0));}for(const link of links){if(!roots[link.target])continue;try{await link.node.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:roots[link.target].id,navigation:'NAVIGATE',transition:null,preserveScrollPosition:false}]}]);}catch(e){warnings.push('原型连线未设置：'+link.node.name+' → '+link.target+' / '+String(e));}}const targets=Object.values(roots);if(targets.length)figma.viewport.scrollAndZoomIntoView([targets[0]]);const uniqueWarnings=[...new Set(warnings)];status('已创建 '+selected.length+' 个画面。请核对中文字体、文字边界与原型连接。',100);figma.ui.postMessage({type:'done',created:createdIds.length,frames:selected.length,pageId:page.id,warnings:uniqueWarnings});}catch(e){status('停止：'+String(e),null);figma.ui.postMessage({type:'error',message:String(e),created:createdIds.length,warnings:[...new Set(warnings)]});}finally{running=false;}};
'''.replace('__DESIGN__',json.dumps(D,ensure_ascii=False,separators=(',',':')))
P=ROOT/'figma-plugin';P.mkdir(exist_ok=True)
(P/'code.js').write_text(plugin)
(P/'ui.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><style>body{font:13px/1.7 system-ui,sans-serif;padding:18px;color:#1e2a3b;background:#fffdf9}h2{font-size:20px;margin:0 0 12px}select,button{font:inherit;border-radius:8px;padding:9px 12px;border:1px solid #dedcd5}select{width:100%;background:white}button{margin:12px 6px 0 0;background:#284c56;color:white;cursor:pointer}button.secondary{background:white;color:#284c56}#log{height:92px;overflow:auto;white-space:pre-wrap;background:#f6f4f0;padding:10px;border-radius:8px;font-size:11px}progress{width:100%}small{color:#667281}</style><h2>NovelCraft V4 · 原生设计导入</h2><p>新建一个页面；不覆盖现有内容。文字与矢量图可编辑，按钮/状态为组件。全量画面较多，首次建议先导入核心流程。</p><select id="scope"><option value="core">核心流程（14 稿）</option><option value="all">全部 49 稿</option><option value="map">地图与媒体（10 稿）</option><option value="mobile">移动端（5 稿）</option></select><div><button id="create">开始导入</button><button class="secondary" id="cancel">停止新增</button><button class="secondary" id="close">关闭</button></div><p id="status">离线数据，不访问网络或真实小说。</p><progress id="progress" max="100" value="0"></progress><pre id="log">本插件未在本轮 Figma 环境执行；请导入后检查字体和连线。</pre><script>const send=t=>parent.postMessage({pluginMessage:{type:t,scope:document.querySelector('#scope').value}},'*');for(const id of ['create','cancel','close'])document.getElementById(id).onclick=()=>send(id);onmessage=e=>{const m=e.data.pluginMessage;if(!m)return;if(m.type==='status'){document.querySelector('#status').textContent=m.text;if(m.progress!==null)document.querySelector('#progress').value=m.progress}if(m.type==='done'||m.type==='error')document.querySelector('#log').textContent=JSON.stringify(m,null,2)};</script></html>''')
manifest={'name':'NovelCraft V4 HiFi Importer','api':'1.0.0','main':'code.js','ui':'ui.html','editorType':['figma'],'documentAccess':'dynamic-page','networkAccess':{'allowedDomains':['none']}}
(P/'manifest.template.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
(P/'README.md').write_text('''# 原生 Figma 重建插件

状态：代码已提供，本轮因 Figma MCP 额度限制未在 Figma 中执行。不能把离线测试当成原生运行通过。

## 使用

在 Figma Design 的开发插件入口创建一个带 UI 的本地插件，由 Figma 生成真实 `id` 和 `manifest.json`。将本目录 `code.js`、`ui.html` 放入该插件文件夹；把 `manifest.template.json` 的字段合并到它生成的 manifest 中，保留 Figma 分配的 `id`。不要编造插件 ID。然后在开发插件菜单运行。

首次建议选择“核心流程”。执行会新建一个页面，不修改现有页面。再次执行会再新建页面，不自动覆盖或删除旧稿；停止会保留已经创建的内容。选择全部将建立 49 个画板和本地组件/变量，耗时取决于 Figma 环境。

无需模型 Key，不访问网络，不含真实小说或账号数据，不包含字体文件。优先使用 Noto Sans SC / Noto Serif SC；环境缺字体时回退并报告。回退后要核对字宽与溢出。

## 可编辑性

文本为原生 text；容器为 frame；插画是矢量路径而非整页截图；按钮和状态使用本地组件实例及 Auto Layout；语义颜色绑定本地 variables。大屏页面是固定 HiFi 排布，响应式参考独立手机画板，不声称整个页面已做生产级 Auto Layout。

同一范围内的热点尝试创建原型连线；指向未导入画面的热点不会连接。连线失败会记录，不伪报成功。主文件 `design.json` 和 SVG 是一致的离线基线。

## 核对

核对 DS00、S06、S09、S20、S33、S37 的中文字体和画板边界；地图侧栏不遮挡关键标签；手机 sheet 不压住正文；实例文字保持居中；“永久删除”等按钮仅连接设计画面，不执行业务。

官方 manifest 说明：https://developers.figma.com/docs/plugins/manifest/
''')
print('prototype',len(html_doc.encode()),'bytes; plugin',len(plugin.encode()),'bytes')
