"""
知识治理子包：能力策略注册表、版本化契约、范围冻结引擎与治理执行器。

公共出口经 evidence contracts/facade 链对外；导演/审查/返修的 LLM 步骤全部走
managed harness，provenance 进入 task result 的 managed_llm_steps。
"""

from modules.evidence.compilation.knowledge.contracts import (
    AUDIT_FINDING_KINDS,
    AUDIT_SEVERITIES,
    AUDIT_VERDICTS,
    BLOCKING_SEVERITIES,
    DIRECTOR_DISPOSITIONS,
    GOVERNANCE_STAGES,
    KNOWLEDGE_POLICY_VERSION,
    REVIEW_STATUSES,
    KnowledgeAuditFinding,
    KnowledgeAuditReceipt,
    KnowledgeContractError,
    KnowledgeContractVersionError,
    KnowledgeDimensionCoverage,
    KnowledgeDirectorDisposition,
    KnowledgeDirectorPlan,
    KnowledgeReviewProjection,
    KnowledgeScopeReceipt,
    KnowledgeSourceEntry,
    KnowledgeSubject,
    knowledge_canonical_hash,
)
from modules.evidence.compilation.knowledge.group import (
    GroupSource,
    build_group_scope,
    govern_group_output,
    serialize_group_output,
)
from modules.evidence.compilation.knowledge.llm_schemas import (
    AuditDimensionCheck,
    AuditFindingOutput,
    AuditVerdictOutput,
    DirectorShardDisposition,
    DirectorShardPlan,
)
from modules.evidence.compilation.knowledge.policies import (
    CAPABILITY_REGISTRY,
    CapabilityKnowledgePolicy,
    capability_ids,
    get_capability_policy,
    iter_capabilities,
    require_capability_policy,
    validate_registry,
)
from modules.evidence.compilation.knowledge.projection import (
    governance_stage_payload,
    knowledge_review_payload,
    legacy_unchecked_payload,
    redact_hidden_phrases,
    require_knowledge_review_for_adoption,
    sanitize_audit_receipt,
)
from modules.evidence.compilation.knowledge.scope import (
    KnowledgeScopeBuild,
    build_scope_receipt,
    ensure_no_excluded_backflow,
    knowledge_subject_from_options,
    reduce_dispositions,
    require_scope_complete,
    scope_continuation_token,
    shard_source_keys,
)
from modules.evidence.compilation.knowledge.workflow import (
    REPAIR_INSTRUCTION_TEMPLATE,
    GovernedGenerationOutcome,
    GovernedWorkflowHooks,
    apply_director_plan,
    run_governed_generation,
    run_knowledge_audit,
    run_knowledge_director,
)

__all__ = [
    "AUDIT_FINDING_KINDS",
    "AUDIT_SEVERITIES",
    "AUDIT_VERDICTS",
    "BLOCKING_SEVERITIES",
    "CAPABILITY_REGISTRY",
    "DIRECTOR_DISPOSITIONS",
    "GOVERNANCE_STAGES",
    "KNOWLEDGE_POLICY_VERSION",
    "REVIEW_STATUSES",
    "AuditDimensionCheck",
    "AuditFindingOutput",
    "AuditVerdictOutput",
    "CapabilityKnowledgePolicy",
    "DirectorShardDisposition",
    "DirectorShardPlan",
    "GovernedGenerationOutcome",
    "GovernedWorkflowHooks",
    "GroupSource",
    "KnowledgeAuditFinding",
    "KnowledgeAuditReceipt",
    "KnowledgeContractError",
    "KnowledgeContractVersionError",
    "KnowledgeDimensionCoverage",
    "KnowledgeDirectorDisposition",
    "KnowledgeDirectorPlan",
    "KnowledgeReviewProjection",
    "KnowledgeScopeBuild",
    "KnowledgeScopeReceipt",
    "KnowledgeSourceEntry",
    "KnowledgeSubject",
    "REPAIR_INSTRUCTION_TEMPLATE",
    "apply_director_plan",
    "build_group_scope",
    "build_scope_receipt",
    "capability_ids",
    "ensure_no_excluded_backflow",
    "get_capability_policy",
    "govern_group_output",
    "governance_stage_payload",
    "iter_capabilities",
    "knowledge_canonical_hash",
    "knowledge_review_payload",
    "knowledge_subject_from_options",
    "legacy_unchecked_payload",
    "redact_hidden_phrases",
    "reduce_dispositions",
    "require_capability_policy",
    "require_knowledge_review_for_adoption",
    "require_scope_complete",
    "run_governed_generation",
    "run_knowledge_audit",
    "run_knowledge_director",
    "sanitize_audit_receipt",
    "serialize_group_output",
    "scope_continuation_token",
    "shard_source_keys",
    "validate_registry",
]
