<template>
  <Teleport to="body">
    <div v-if="quick.state.open" ref="overlayRef" class="vue-map-dialog-backdrop" role="presentation" @keydown="onKeydown" @focusin="onFocusin">
      <section ref="dialogRef" class="vue-map-dialog vue-map-dialog--wide" role="dialog" aria-modal="true" aria-labelledby="map-quick-title" :aria-busy="quick.state.saving" tabindex="-1">
        <header><h2 id="map-quick-title">快速创建地图</h2><button type="button" class="btn btn-sm" aria-label="关闭" :disabled="quick.state.saving" @click="requestClose">×</button></header>
        <fieldset class="vue-map-dialog__body map-quick-create" :disabled="quick.state.saving">
          <p v-if="quick.state.loading" class="map-muted-text">正在生成布局预览...</p>
          <div v-if="quick.state.error" class="alert alert-warning">{{ quick.state.error }}</div>
          <template v-if="quick.state.context && quick.state.preview">
            <div class="map-quick-settings">
              <div class="form-group"><label for="map-quick-target">创建目标</label><select id="map-quick-target" class="form-select" :value="quick.state.target" :disabled="Boolean(quick.state.replaceMapId)" @change="quick.setTarget($event.target.value)"><option value="world">世界地图</option><option value="detail">地点详图</option><option value="drilldown">下钻地图</option></select></div>
              <div v-if="quick.state.target !== 'world'" class="form-group"><label for="map-quick-parent-entity">父地点</label><select id="map-quick-parent-entity" class="form-select" :value="quick.state.parentEntityId || ''" :disabled="Boolean(quick.state.replaceMapId)" @change="quick.changeSetting('parentEntityId', $event.target.value || null)"><option value="">请选择</option><option v-for="item in quick.state.context.locations || []" :key="item.id" :value="item.id">{{ item.name }}</option></select></div>
              <div v-if="quick.state.target === 'drilldown'" class="form-group"><label for="map-quick-parent-map">父地图</label><select id="map-quick-parent-map" class="form-select" :value="quick.state.parentMapId || ''" :disabled="Boolean(quick.state.replaceMapId)" @change="quick.changeSetting('parentMapId', $event.target.value || null)"><option value="">请选择</option><option v-for="item in quick.state.context.existing_maps || []" :key="item.id" :value="item.id">{{ item.name }}</option></select></div>
              <div class="form-group"><label for="map-quick-replace">创建方式</label><select id="map-quick-replace" class="form-select" :value="quick.state.replaceMapId || ''" @change="quick.setReplacement($event.target.value || null)"><option value="">创建新地图</option><option v-for="item in quick.state.context.existing_maps || []" :key="item.id" :value="item.id">替换：{{ item.name }}（{{ item.grid_width }}×{{ item.grid_height }}）</option></select></div>
              <div class="form-group"><label for="map-quick-name">地图名称</label><input id="map-quick-name" v-model="quick.state.mapName" class="form-input" :disabled="Boolean(quick.state.replaceMapId)" @input="quick.state.mapNameTouched = true" /></div>
              <div class="form-group"><label for="map-quick-type">地图类型</label><select id="map-quick-type" class="form-select" :value="quick.state.mapType" :disabled="Boolean(quick.state.replaceMapId)" @change="quick.changeSetting('mapType', $event.target.value)"><option v-for="type in ['world','city','region','dungeon']" :key="type" :value="type">{{ type }}</option></select></div>
              <div class="form-group"><label>网格</label><div class="map-quick-grid-inputs"><input id="map-quick-width" class="form-input" type="number" min="1" max="200" :value="quick.state.gridWidth" :disabled="Boolean(quick.state.replaceMapId)" aria-label="地图网格宽度" @change="quick.changeSetting('gridWidth', Number($event.target.value))" /><span>×</span><input id="map-quick-height" class="form-input" type="number" min="1" max="200" :value="quick.state.gridHeight" :disabled="Boolean(quick.state.replaceMapId)" aria-label="地图网格高度" @change="quick.changeSetting('gridHeight', Number($event.target.value))" /></div></div>
              <div class="form-group"><label for="map-quick-template">底图模板</label><select id="map-quick-template" class="form-select" :value="quick.state.baseTemplate" :disabled="Boolean(quick.state.replaceMapId)" @change="quick.changeSetting('baseTemplate', $event.target.value)"><option value="blank">空白</option><option value="continent">大陆</option><option value="islands">群岛</option></select></div>
              <div class="form-group"><label for="map-quick-extra-search">添加其他已采用地点</label><input v-model="extraSearch" class="form-input" id="map-quick-extra-search" type="search" placeholder="搜索地点名称" /><div class="map-quick-extra-row"><select v-model="extraLocationId" id="map-quick-extra" class="form-select" aria-label="选择其他已采用地点"><option value="">选择地点...</option><option v-for="item in extraOptions" :key="item.id" :value="item.id">{{ item.name }}</option></select><button type="button" class="btn btn-sm" id="map-quick-extra-add" :disabled="!extraLocationId" @click="addExtra">添加</button></div></div>
            </div>
            <label class="map-layer-toggle"><input id="map-quick-include-candidates" type="checkbox" :checked="quick.state.includeCandidates" @change="quick.setIncludeCandidates($event.target.checked)" />包含待处理地点</label>
            <div v-for="warning in quick.state.preview.warnings || []" :key="warning" class="alert alert-warning">{{ warning }}</div>
            <div class="view-header map-toolbar"><div class="view-header__title">快速放置</div><div class="view-header__actions"><button type="button" id="map-quick-undo" class="btn btn-sm" :disabled="!quick.state.history.length" @click="quick.undo">撤销</button><button type="button" id="map-quick-redo" class="btn btn-sm" :disabled="!quick.state.redo.length" @click="quick.redo">重做</button><span class="view-header__count">已选 {{ selectedCount }} / 共 {{ placeableLayouts.length }}</span></div></div>
            <div class="map-quick-canvas-wrap"><canvas ref="canvas" id="map-quick-canvas" class="map-quick-canvas" width="920" height="420" aria-label="地点布局画布" @pointerdown="pointerDown" @pointermove="pointerMove" @pointerup="pointerEnd" @pointercancel="pointerEnd"></canvas><p class="map-quick-meta">拖动已采用地点调整中心格；待处理地点仅供预览。</p></div>
            <table class="data-table"><thead><tr><th><input id="map-quick-select-all" type="checkbox" :checked="allSelected" :disabled="!placeableLayouts.length" aria-label="全选可放置地点" @change="quick.setAllSelected($event.target.checked)" /></th><th>地点</th><th>位置</th><th>半径</th><th>状态</th><th>调整</th></tr></thead><tbody><tr v-for="layout in quick.state.activeLayouts" :key="layout.location_entity_id" :class="{ 'map-quick-row-unselected': !quick.state.selectedIds.has(layout.location_entity_id), 'is-candidate': quick.isCandidate(layout) }"><td><input type="checkbox" data-action="map-quick-select" :data-id="layout.location_entity_id" :checked="quick.state.selectedIds.has(layout.location_entity_id)" :disabled="quick.isCandidate(layout)" :aria-label="`选择地点 ${quick.locationName(layout.location_entity_id)}`" @change="quick.toggleSelection(layout.location_entity_id, $event.target.checked)" /></td><td>{{ quick.locationName(layout.location_entity_id) }}</td><td>{{ layout.center_hex_q }}, {{ layout.center_hex_r }}</td><td><button type="button" class="btn btn-sm map-quick-row-control" data-action="map-quick-radius" :disabled="!editable(layout)" :aria-label="`缩小地点 ${quick.locationName(layout.location_entity_id)} 的半径`" @click="quick.resizeLocation(layout.location_entity_id, 'decrease')">-</button>{{ layout.occupy_radius }}<button type="button" class="btn btn-sm map-quick-row-control" data-action="map-quick-radius" :disabled="!editable(layout)" :aria-label="`扩大地点 ${quick.locationName(layout.location_entity_id)} 的半径`" @click="quick.resizeLocation(layout.location_entity_id, 'increase')">+</button></td><td>{{ quick.isCandidate(layout) ? '待处理 · 只读预览' : quick.state.selectedIds.has(layout.location_entity_id) ? layout.locked ? '已锁定' : '可拖动' : '未选择' }}</td><td><button type="button" v-for="move in MOVES" :key="move.label" class="btn btn-sm map-quick-row-control" data-action="map-quick-move" :disabled="!editable(layout)" :aria-label="moveAriaLabel(move, layout.location_entity_id)" @click="quick.moveLocation(layout.location_entity_id, move.q, move.r)">{{ move.label }}</button><button type="button" class="btn btn-sm map-quick-row-control" data-action="map-quick-lock" :disabled="!quick.state.selectedIds.has(layout.location_entity_id) || quick.isCandidate(layout)" :aria-label="`${layout.locked ? '解锁' : '锁定'}地点 ${quick.locationName(layout.location_entity_id)}`" @click="quick.toggleLock(layout.location_entity_id)">{{ layout.locked ? '解锁' : '锁定' }}</button></td></tr><tr v-if="!quick.state.activeLayouts.length"><td colspan="6">暂无可放置地点</td></tr></tbody></table>
          </template>
        </fieldset>
        <footer><button type="button" class="btn" :disabled="quick.state.saving" @click="requestClose">取消</button><button type="button" class="btn btn-primary" :disabled="quick.state.loading || quick.state.saving || !selectedCount" @click="quick.submit">{{ quick.state.saving ? '创建中…' : '创建' }}</button></footer>
      </section>
    </div>
  </Teleport>
</template>

<script setup>
import { computed, nextTick, ref, watch } from "vue"
import { useModalDialog } from "../../../composables/useModalDialog.js"
const props = defineProps({ quick: { type: Object, required: true } })
const requestClose = () => props.quick.close()
const { overlayRef, dialogRef, onKeydown, onFocusin } = useModalDialog({ isOpen: () => props.quick.state.open, requestClose, canClose: () => !props.quick.state.saving })
const canvas = ref(null)
const extraSearch = ref("")
const extraLocationId = ref("")
const dragId = ref(null)
const MOVES = [{ label: "←", q: -1, r: 0 }, { label: "→", q: 1, r: 0 }, { label: "↑", q: 0, r: -1 }, { label: "↓", q: 0, r: 1 }]
const MOVE_LABELS = { "←": "向左", "→": "向右", "↑": "向上", "↓": "向下" }
const placeableLayouts = computed(() => props.quick.state.activeLayouts.filter((item) => !props.quick.isCandidate(item)))
const selectedCount = computed(() => placeableLayouts.value.filter((item) => props.quick.state.selectedIds.has(item.location_entity_id)).length)
const allSelected = computed(() => placeableLayouts.value.length > 0 && selectedCount.value === placeableLayouts.value.length)
const activeIds = computed(() => new Set(props.quick.state.activeLayouts.map((item) => item.location_entity_id)))
const extraOptions = computed(() => (props.quick.state.context?.locations || []).filter((item) => !activeIds.value.has(item.id) && item.name?.toLowerCase().includes(extraSearch.value.trim().toLowerCase())))
function editable(layout) { return props.quick.state.selectedIds.has(layout.location_entity_id) && !layout.locked && !props.quick.isCandidate(layout) }
function moveAriaLabel(move, locationId) { return `${MOVE_LABELS[move.label]}移动地点 ${props.quick.locationName(locationId)}` }
async function addExtra() { const id = extraLocationId.value; if (await props.quick.addExtraLocation(id)) { extraLocationId.value = ""; extraSearch.value = "" } }
function point(q, r) { const el = canvas.value; const width = Math.max(320, el?.clientWidth || 920); const height = Math.max(240, el?.clientHeight || 420); const gridWidth = Math.max(1, Number(props.quick.state.preview?.map?.grid_width || props.quick.state.gridWidth)); const gridHeight = Math.max(1, Number(props.quick.state.preview?.map?.grid_height || props.quick.state.gridHeight)); return { x: 24 + (Number(q) / Math.max(1, gridWidth - 1)) * (width - 48), y: 24 + (Number(r) / Math.max(1, gridHeight - 1)) * (height - 48) } }
function draw() { const el = canvas.value; if (!el) return; let ctx; try { ctx = el.getContext("2d") } catch { return } if (!ctx) return; const ratio = window.devicePixelRatio || 1; const width = Math.max(320, el.clientWidth || 920); const height = Math.max(240, el.clientHeight || 420); el.width = Math.round(width * ratio); el.height = Math.round(height * ratio); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); ctx.clearRect(0, 0, width, height); ctx.fillStyle = "#111827"; ctx.fillRect(0, 0, width, height); for (const layout of props.quick.state.activeLayouts) { const p = point(layout.center_hex_q, layout.center_hex_r); const candidate = props.quick.isCandidate(layout); const selected = props.quick.state.selectedIds.has(layout.location_entity_id); ctx.beginPath(); ctx.arc(p.x, p.y, candidate ? 11 : 14, 0, Math.PI * 2); ctx.fillStyle = candidate ? "#64748b" : selected ? "#38bdf8" : "#334155"; ctx.fill(); ctx.strokeStyle = layout.locked ? "#f59e0b" : candidate ? "#94a3b8" : "#e2e8f0"; ctx.lineWidth = layout.locked ? 3 : 1.5; ctx.stroke(); ctx.font = "12px sans-serif"; ctx.textAlign = "center"; ctx.fillStyle = "#f8fafc"; ctx.fillText(props.quick.locationName(layout.location_entity_id), p.x, p.y - 20) } }
function eventHex(event) { const el = canvas.value; const rect = el.getBoundingClientRect(); const width = Math.max(320, rect.width || el.clientWidth || 920); const height = Math.max(240, rect.height || el.clientHeight || 420); const gridWidth = Math.max(1, Number(props.quick.state.preview?.map?.grid_width || props.quick.state.gridWidth)); const gridHeight = Math.max(1, Number(props.quick.state.preview?.map?.grid_height || props.quick.state.gridHeight)); const x = Math.max(24, Math.min(width - 24, event.clientX - rect.left)); const y = Math.max(24, Math.min(height - 24, event.clientY - rect.top)); return [Math.round(((x - 24) / Math.max(1, width - 48)) * (gridWidth - 1)), Math.round(((y - 24) / Math.max(1, height - 48)) * (gridHeight - 1))] }
function pointerDown(event) { if (props.quick.state.saving) return; const rect = canvas.value.getBoundingClientRect(); const layout = props.quick.state.activeLayouts.find((item) => { if (!editable(item)) return false; const p = point(item.center_hex_q, item.center_hex_r); return Math.hypot(event.clientX - rect.left - p.x, event.clientY - rect.top - p.y) <= 24 }); if (!layout) return; props.quick.pushHistory(); dragId.value = layout.location_entity_id; canvas.value.setPointerCapture?.(event.pointerId); event.preventDefault() }
function pointerMove(event) { if (props.quick.state.saving || !dragId.value) return; const [q, r] = eventHex(event); props.quick.moveLocationTo(dragId.value, q, r); draw() }
function pointerEnd(event) { if (!dragId.value) return; canvas.value.releasePointerCapture?.(event.pointerId); dragId.value = null }
watch(() => [props.quick.state.open, props.quick.state.activeLayouts, [...props.quick.state.selectedIds], props.quick.state.preview], async () => { await nextTick(); draw() }, { deep: true })
</script>

<style scoped>
.vue-map-dialog-backdrop { position: fixed; inset: 0; z-index: 1100; display: grid; place-items: center; padding: 24px; background: rgba(2, 6, 23, .68); }
.vue-map-dialog { display: grid; grid-template-rows: auto minmax(0, 1fr) auto; width: min(96vw, 1100px); max-height: 94vh; overflow: hidden; border: 1px solid var(--border-color); border-radius: var(--radius-lg); background: var(--surface-primary); box-shadow: var(--shadow-xl); }
.vue-map-dialog > header, .vue-map-dialog > footer { display: flex; align-items: center; justify-content: space-between; gap: var(--space-3); padding: var(--space-4); border-bottom: 1px solid var(--border-color); }
.vue-map-dialog > footer { justify-content: flex-end; border-top: 1px solid var(--border-color); border-bottom: 0; }
.vue-map-dialog__body { overflow: auto; padding: var(--space-4); min-inline-size: 0; border: 0; margin: 0; }
/* 局部组件自适应断点保留（design-standard.md §6：全局仅 760/1100 两档，此处为组件级微调） */
@media (max-width: 390px) {
  .map-quick-row-control { min-width: 40px; min-height: 40px; }
  .vue-map-dialog > header .btn { min-width: 40px; min-height: 40px; }
  .vue-map-dialog > footer .btn { min-height: 44px; }
}
</style>
