<template>
  <div v-if="timeline.loading" class="map-dynamic-section"><h4>Scene 时间轴</h4><p class="map-muted-text">正在组装正式世界状态...</p></div>
  <template v-else-if="timeline.data?.scenes?.length">
    <div class="map-dynamic-section map-timeline-panel" :class="{ 'is-low-motion': lowMotion }">
      <div class="map-playback-header"><h4>Scene 时间轴</h4><button class="btn btn-sm" :disabled="editing" :data-action="timeline.playing ? 'map-timeline-stop' : 'map-timeline-start'" @click="$emit(timeline.playing ? 'stop' : 'start')">{{ timeline.playing ? '暂停' : '播放' }}</button></div>
      <div class="map-timeline-controls">
        <div class="map-timeline-stepper"><button class="btn btn-sm" :disabled="timeline.activeIndex <= 0" aria-label="上一个 Scene" @click="$emit('step', -1)">←</button><select class="form-select" aria-label="选择 Scene" :value="timeline.activeIndex" @change="$emit('position', Number($event.target.value))"><option v-for="(scene, index) in timeline.data.scenes" :key="scene.scene_index" :value="index">{{ sceneLabel(scene.scene_index) }}</option></select><button class="btn btn-sm" :disabled="timeline.activeIndex >= timeline.data.scenes.length - 1" aria-label="下一个 Scene" @click="$emit('step', 1)">→</button></div>
        <input class="map-timeline-cursor" type="range" min="0" :max="Math.max(0, timeline.data.scenes.length - 1)" :value="timeline.activeIndex" aria-label="Scene 时间游标" @change="$emit('position', Number($event.target.value))" />
        <div class="map-timeline-caption"><span>{{ sceneLabel(activeScene?.scene_index) }}</span><span>{{ activeScene?.delta_count || 0 }} 项变化 · {{ activeScene?.conflict_count || 0 }} 个冲突</span></div>
        <div class="map-timeline-options"><label>播放节奏<select class="form-select" :value="timeline.speedMs" @change="$emit('speed', Number($event.target.value))"><option :value="2400">舒缓</option><option :value="1600">标准</option><option :value="900">紧凑</option></select></label><label class="map-timeline-candidate-toggle"><input type="checkbox" :checked="timeline.includeCandidates" @change="$emit('candidates', $event.target.checked)" />待处理预览</label></div>
        <div class="map-timeline-tracks" role="group" aria-label="时间轴轨道"><label v-for="track in MAP_TIMELINE_TRACKS" :key="track.key"><input type="checkbox" :checked="timeline.selectedTracks[track.key] !== false" @change="$emit('track', track.key, $event.target.checked)" />{{ track.label }}</label></div>
        <span v-if="lowMotion" class="map-timeline-motion-note">低动效：逐 Scene 切换</span>
      </div>
      <p v-if="timeline.stateLoading" class="map-muted-text">正在加载 {{ sceneLabel(timeline.sceneIndex) }} 的正式状态...</p>
      <div v-else-if="timeline.stateError" class="alert alert-warning">{{ timeline.stateError }}</div>
      <section v-else class="map-timeline-state"><h5>正式状态</h5><p v-if="!stateItems.length" class="map-muted-text">当前 Scene 暂无已结构化的正式状态。</p><article v-for="item in stateItems.slice(0, 8)" :key="item.id || item.item_id || JSON.stringify(item)" class="map-timeline-state-item is-canonical"><div class="map-dynamic-title">{{ dynamicTitle(item, item.target_name || item.dynamic_type || '地图对象') }}</div><div class="map-dynamic-meta">{{ mapDynamicTrackLabel(item) }} · 已采用 · {{ mapDynamicNormalizationLabel(item.normalization_state) }}</div><div class="map-dynamic-source">{{ mapSourceText(formatMapDynamicValue(item.normalized_value, '正式状态已记录')) }}</div></article></section>
      <section v-if="timeline.includeCandidates" class="map-timeline-candidates"><h5>待处理预览</h5><p v-if="!candidateItems.length" class="map-muted-text">当前 Scene 没有待处理候选。</p><article v-for="item in candidateItems.slice(0, 6)" :key="item.id || item.item_id" class="map-timeline-state-item is-candidate"><div class="map-dynamic-title">{{ dynamicTitle(item, item.target_name || item.title || item.dynamic_type || '待处理地图对象') }}</div><div class="map-dynamic-meta">{{ mapDynamicTrackLabel(item) }} · {{ fragmentLabel(item) }} · 只读预览</div><div class="map-dynamic-source">{{ mapSourceText(formatMapDynamicValue(item.normalized_value, item.evidence_text || '等待作者判断')) }}</div></article></section>
      <section v-if="conflicts.length" class="map-timeline-conflicts"><h5>同一叙事时点冲突</h5><article v-for="item in conflicts.slice(0, 5)" :key="item.id || item.item_id" class="map-timeline-state-item is-conflict"><div class="map-dynamic-title">{{ item.target_name || item.dynamic_type || '地图状态冲突' }}</div><div class="map-dynamic-source">{{ fragmentLabel(item) }}；存在 {{ item.values?.length || 2 }} 个互相矛盾的正式值，当前状态未替作者做选择。</div></article></section>
    </div>
    <section v-if="timeline.data.continuity_issues?.length" class="map-dynamic-section map-continuity-panel"><div class="map-playback-header"><h4>空间连续性</h4><span>{{ timeline.data.continuity_issues.length }} 项待核对</span></div><article v-for="issue in timeline.data.continuity_issues.slice(0, 8)" :key="issue.issue_key" class="map-continuity-issue" :class="issue.severity === 'danger' || issue.severity === 'error' ? 'is-danger' : 'is-warning'"><div class="map-dynamic-title">{{ issue.target_name || continuityLabel(issue.issue_type) }}</div><div class="map-dynamic-meta">{{ continuitySceneRange(issue) }}{{ issue.distance_hex == null ? '' : ` · ${issue.distance_hex} 格` }}</div><div class="map-dynamic-source">{{ mapSourceText(issue.message || continuityLabel(issue.issue_type)) }}</div><div class="map-dynamic-actions"><button class="btn btn-sm" @click="$emit('continuity-focus', issue, 'from')">定位起点</button><button class="btn btn-sm" @click="$emit('continuity-focus', issue, 'to')">定位终点</button><button class="btn btn-sm" @click="$emit('continuity-evidence', issue)">查看证据</button><button v-if="issue.suggested_observation" class="btn btn-sm btn-primary" @click="$emit('continuity-explain', issue)">补充解释</button></div></article></section>
  </template>
  <div v-else class="map-dynamic-section map-playback-panel"><div class="map-playback-header"><h4>电影化播放</h4><button v-if="playback.playback" class="btn btn-sm" @click="$emit(playback.playing ? 'playback-stop' : 'playback-start')">{{ playback.playing ? '停止' : '播放' }}</button></div><div v-if="timeline.error" class="map-timeline-fallback"><span>类型化时间轴暂不可用，已保留旧播放。</span><button class="btn btn-sm" @click="$emit('retry')">重试</button></div><article v-if="playbackEvent" class="map-dynamic-item"><div class="map-dynamic-title">{{ playbackEvent.title }}</div><div class="map-dynamic-meta">{{ playbackEvent.time_label }} · {{ playbackEvent.status_label || '待判断' }}</div><div class="map-dynamic-source">{{ playbackEvent.change_summary || playbackEvent.source_summary }}</div></article><p v-else class="map-muted-text">暂无可播放动态</p></div>
</template>

<script setup>
import { computed } from "vue"
import { MAP_TIMELINE_TRACKS, filterTimelineItems, formatMapDynamicValue, mapDynamicNormalizationLabel, mapDynamicTrackLabel, timelineItemsAtScene } from "../../../../views/mapTimelineProjection.js"
import { mapSceneLabel, mapSourceText, normalizeEmbeddedSceneLabel } from "../mapModel.js"
const props = defineProps({ timeline: { type: Object, required: true }, playback: { type: Object, required: true }, lowMotion: Boolean, editing: Boolean })
defineEmits(["start", "stop", "step", "position", "speed", "candidates", "track", "retry", "playback-start", "playback-stop", "continuity-focus", "continuity-evidence", "continuity-explain"])
const activeScene = computed(() => props.timeline.data?.scenes?.[props.timeline.activeIndex] || null)
const stateItems = computed(() => filterTimelineItems(props.timeline.stateAt?.items || [], props.timeline.selectedTracks))
const candidateItems = computed(() => timelineItemsAtScene(props.timeline.data?.candidates || [], props.timeline.sceneIndex, props.timeline.selectedTracks))
const conflicts = computed(() => timelineItemsAtScene([...(props.timeline.data?.conflicts || []), ...(props.timeline.stateAt?.conflicts || [])], props.timeline.sceneIndex, props.timeline.selectedTracks))
const playbackEvent = computed(() => props.playback.playback?.events?.[props.playback.activeIndex] || props.playback.playback?.events?.[0] || null)
function sceneLabel(value) { return mapSceneLabel(value) }
function dynamicTitle(item, fallback) { return normalizeEmbeddedSceneLabel(fallback, item) }
function fragmentLabel(item) { const sequence = item.scene_sequence ?? item.time_anchor?.scene_sequence; return sequence == null ? "Scene 内顺序待补充" : `片段 ${Number(sequence) + 1}` }
function continuitySceneRange(issue) { if (issue.from_scene_index !== issue.to_scene_index) return `${sceneLabel(issue.from_scene_index)} → ${sceneLabel(issue.to_scene_index)}`; const from = issue.from_scene_sequence; const to = issue.to_scene_sequence; return from == null && to == null ? sceneLabel(issue.to_scene_index) : `${sceneLabel(issue.to_scene_index)} · 片段 ${Number(from ?? to) + 1} → ${Number(to ?? from) + 1}` }
function continuityLabel(type) { return ({ same_scene_conflict: "同一 Scene 的位置冲突", missing_anchor: "位置锚点缺失", route_unknown: "路线信息不足", no_route: "未找到连通路线", blocked_route: "移动经过受阻线路", path_revision_mismatch: "线路版本已经变化" })[type] || "空间连续性待核对" }
</script>
